#!/usr/bin/env python

import BaseHTTPServer
import SimpleHTTPServer
import os.path
import sys
server_address = ("", 8888)
PATH2 = 'out/'

try:
    if sys.argv[1] == 'en':
        PATH1 = 'out/blog/en/'
    elif sys.argv[1] == 'pl':
        PATH1 = 'out/blog/pl/'
    else:
        PATH1 = PATH2
except IndexError:
    PATH1 = PATH2

class MyRequestHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):
    def translate_path(self, path):
        if path.endswith('/'):
            new_path = PATH1 + path + 'index.html'
        elif os.path.isfile(PATH1 + path):
            new_path = PATH1 + path
        else:
            new_path = PATH2 + path
        return SimpleHTTPServer.SimpleHTTPRequestHandler.translate_path(self, new_path)

httpd = BaseHTTPServer.HTTPServer(server_address, MyRequestHandler)
httpd.serve_forever()
