# -*- typo-language: Polish; -*-

* 2022

** 1. Robert M. Wegner, Niebo ze stali
** 2-4. Andrzej Sapkowski, Trylogia husycka (Narrenturm; Boży bojownicy; Lux perpetua)
** 5. Hervé Le Tellier, Anomalia
** 6. Robert M. Wegner, Pamięć wszystkich słów
** 7. Tadeusz Boy-Żeleński, Brązownicy
** 8. Michał Markowski, Ożeniłem się z brzydką dziewczyną
** 9. H. P. Lovecraft, Zgroza w Dunwich i inne przerażające opowieści
** 10. Ursula K. Le Guin, Słowo „las” znaczy „świat”
** 11. Konrad Walewski (red.), Kroki w nieznane 2005

SF bierze na warsztat przyszłość jako dyżurny temat. Jest pewnym paradoksem, że lektura tej antologii była dla mnie wyprawą w przeszłość. Konkretnie w nastoletniość, w czasy późnej podstawówki i wczesnego liceum, kiedy kupowałem (przy korzystnych układach zawartości kieszonkowego i dostępności w kioskach) „Nową Fantastykę” i „Fenixa”, a potem już tylko „NF”, i czytałem wszystko jak leci, i poznawałem nazwiska: Bradbury, Dick, Tiptree jr., Bułyczow…

Dotarło do mnie, że od tamtej pory właściwie nie czytałem fantastycznej krótkiej formy. Powieści, proszę bardzo, dużo i często. Ale opowiadania? Not so much. I tak to trwało, dopóki niefortunnym zbiegiem okoliczności wpadła mi w ręce cała kolekcja „Kroków w nieznane”, wszystkie tomy, i te PRL-owskie, i te z lat 2000. A o głównym czynniku sprawczym owego zbiegu okoliczności można już mówić tylko w czasie przeszłym.

Hello past, my old friend.

Na pierwszy ogień, trochę przypadkiem, poszedł tom z 2005, pierwszy po reaktywacji. I jest nieźle, choć bez wielkich odkryć.

Parę opowiadań zapamiętam na dłużej. Otwierające tom „Siedemdziesiąt dwie litery” Chianga, w ciekawy sposób eksplorujące motywy okołokabalistyczne; nostalgicznie amerykańskie, space-operowe opowiadanko Doctorowa, z którym to jest mój pierwszy kontakt i chcę więcej; klimatyczny cyberpunk u Auleya i Di Filippo; wreszcie przecudownie satyryczny tekst „Turysta” Paula Parka, o podróżach w czasie. Nie zawodzą też Rosjanie: u Bułyczowa Wielki Guslar jest dziwny i zabawny jak zawsze, a opowiadanie Wasiljewa o moskiewskim metrze jest ciepłe i na wskroś rosyjskie (frustruje mnie, że wojna i na jego odbiorze odcisnęła piętno).

Poza tym raz jest lepiej, raz gorzej. Taki urok antologii. Ale też miło pamiętać o tym, że nawet jeśli któreś opowiadanie okaże się niezbyt smacznym kąskiem – nie ma co rzucać całego tomu w kąt, bo może następne będzie perełką.

Na minus redakcja: niektóre zdania brzmiały mi koślawo, a i literówek i kiksów interpunkcyjnych wyłowiłem sporą przygarść.

7/10 (oscylujące).

** 12. Christelle Dabos, Zimowe zaręczyny
** 13. Radek Rak, Baśń o wężowym sercu albo wtóre słowo o Jakóbie Szeli

7/10 w mojej prywatnej skali znaczy mniej więcej „dobrze się czyta”, 8/10 – „wciąga jak bagno”, a 9/10 (dycha jest zarezerwowana dla książek życia) – „nie dość, że wciąga jak wyżej, to jeszcze autor wygrywa na czytelniku takie melodie, że aż dusza tańczy”. Język rosyjski ma na to piękne słowo „duszoszczipatielnyj”. I taka jest ta baśń.

Dziewiętnastowieczna Galicja Raka porośnięta jest lasami, zamieszkiwanymi przez stwory, których lepiej nie spotkać na swojej drodze: rozmaite licha, leszych, rodzanice i czarty; a także inne, starsze niż ludzka pamięć. Przede wszystkim zaś węże, na czele z dawno śpiącym Wężowym Królem. A dla galicyjskich chłopów, zwłaszcza dla młodego Kóby Szeli, ich istnienie jest równie oczywiste co kościół w niedzielę, wódka i własna ciężka dola. Skojarzenia leśmianowskie miałem od samego początku: nie zdziwiłbym się, gdyby duch Leśmiana siedział dusiołkiem Rakowi na ramieniu, podszeptywał słowa (bo język tej książki jest niesamowity, potoczysty i rozsnuty) i nucił piosenki ludowe, które od pierwszej strony cytuje autor. Tak.

To jeden z dwóch głównych składników magicznego eliksiru tej baśni. Drugim jest bolesny realizm chłopskiej (Szela powiedziałby: chamskiej) egzystencji, któremu na imię Okrucieństwo, a na drugie Niesprawiedliwość. Z sugestywnym pietyzmem pokazuje Rak relacje między chłopami a panami, barwnie i z dbałością o krwawe szczegóły rysuje sceny drastycznej, bezsensownej przemocy, rozbojów, gwałtów i morderstw. Bo to jest mroczna baśń. Nie dla każdego i nie na każdy nastrój.

I w drodze bohatera przez życie splatają się te światy, ten prawdziwy, który ma do zaoferowania wyłącznie krew, ból, pot i łzy, i ten wężowy, nieprawdziwy, a przecież jakby prawdziwszy – i nie wiadomo, gdzie się kończy jeden, a zaczyna drugi. I w centralnym momencie tej historii, rozdzielającym obie części książki i łączącym je ze sobą niby we wstęgę Möbiusa, zaczynamy zadawać sobie pytania: czy jakakolwiek sprawiedliwość jest w ogóle możliwa? Czy jeden człowiek może cokolwiek zmienić, nawet gdyby dostał do ręki możliwość kształtowania rzeczywistości po pańsku? Czy w ogóle możliwy jest inny porządek rzeczy, niż ten, w którym pan jest panem, a cham chamem? I jak to bywa w dobrej literaturze, nie ma łatwych odpowiedzi.

Przystępując do lektury, o rabacji galicyjskiej wiedziałem tyle co nic; jakieś szczątkowe strzępy wiadomości ze szkoły i niewyraźny powidok Szeli jako widma z „Wesela”. Z radością stwierdzam, że zupełnie to nie przeszkadzało w lekturze. Widać, że risercz został odrobiony porządnie, całość zresztą zaopatrzona jest w posłowie napisane przez historyka i stanowiące rys historyczny chłopskiego powstania. Za to cieszę się, że nie zajrzałem do żadnej recenzji – po lekturze przejrzałem kilka i wszędzie są spojlery.

Wisienką na torcie są odniesienia kulturowe, które autor puszcza do czytelnika: wyłapałem nawiązania od Tolkiena po Lovecrafta, od Reja po Mickiewicza, a przeoczyłem pewnie drugie tyle. Całość to niesamowity, jedyny w swoim rodzaju tygiel. Bardzo polecam.

** 14. Robert M. Wegner, Każde martwe marzenie
** 15. Nick Harkaway, Gnomon

Mam mnóstwo problemów z tą książką. Przeczytałem, a raczej przebrnąłem przez nią w drugim podejściu, półtora roku po pierwszym – i po przeczytaniu czuję głównie ulgę. Może trzeba było dać sobie spokój? Może i tak, ale jest w „Gnomonie” na tyle dużo zapadających w pamięć elementów, że niedokończony siedzi gdzieś z tyłu głowy i przypomina o sobie.

Z pozoru główna oś fabuły wydaje się prosta. Londyn w niedalekiej przyszłości jest stolicą państwa na wskroś policyjnego i inwigilacyjnego, państwa, w którym władza jest skupiona w Systemie. Przestępczość nie istnieje, bo zautomatyzowany System obserwuje obywateli na każdym kroku i wie wszystko o wszystkich. Gdyby komuś zaś przyszło do głowy zrobić coś niepraworządnego, można najdosłowniej zbadać zawartość jego umysłu za pomocą technik neuroprzesłuchania. System jest nie do oszukania i nie można przed nim nic zataić.

Jak to się więc stało, że neuroprzesłuchanie pisarki Diany Hunter, które powinno być rutynowym zabiegiem, zakończyło się jej śmiercią? Inspektorka Systemu, Mielikki Neith, staje przed odpowiedzią na to pytanie. Aby rozwikłać tę zagadkę, musi jednak przejrzeć zapis zawartości mózgu Hunter. I odkrywa tam zupełnie niespodziewane rzeczy…

Mamy więc pierwsze fundamentalne pytanie, przed którym „Gnomon” stawia czytelnika: czy można poświęcić prywatność w imię dobrostanu społeczeństwa? Myliłby się jednak ten, kto sądzi, że to jest tylko cyberpunkowa opowieść o świecie policyjnym. Świat tej książki jest urządzony z dużo większym rozmachem. Jest tu też o rekinach i o świecie wielkiej finansjery; o Etiopii, o jej otwieraniu się na świat i o rozgrywkach politycznych na dworze Hailego Sellasie I w Addis Abebie; o późnym cesarstwie rzymskim i o Augustynie z Hippony; o nadumysłach zamieszkujących wiele ciał; o Komnacie Izydy, istniejącej poza czasem, stwarzanej po wielokroć i przybierającej różne formy; o katabazie i apokatastazie; i o FA LA JI RO JI JA.

Rozumiecie coś z tego? Ja też nie.

No, może trochę. Język tej książki jest skomplikowany i szalenie erudycyjny (dzięki niech będą słownikowi instalowanemu na Kindle’u), a akcja, mimo zagadki z trupem w tle, toczy się nieszczególnie żwawym tempem – narracja w czasie teraźniejszym poświęca dużo uwagi myślom bohaterów, a sceny raczej przepływają jedna w drugą, niż następują po sobie. Czytając, miałem nieustające wrażenie mętliku w głowie i jednego wielkiego WTF.

Mimo to jednak zdarzają się zdania, które są nie tylko najzupełniej jasne, ale też odciskają się w umyśle niezatartym śladem. Jak ten wykład praw człowieka, który ze mną zostanie z „Gnomona”:

> There’s only one fundamental human right, and that is the right to security of person, be it physical or mental. Everything else is contingent on the level of society in which you exist – food, shelter, broadband digital access: all these come later. The only right that cannot be debated – if you acknowledge any kind of right at all – is the one that asserts a boundary at the skin, and says that anything within its boundary is the business of that person and no one else. The right to avoid self-incrimination, the right to die, the right to live, the right to freedom from slavery, freedom of conscience and religion, of opinion, and the right not to be tortured − all these exist as subheadings of that one, simple statement: I am me and I am not yours. No one who believes in rights at all can deny this right. It is the first. Without it, there are no others.

** 16. Bernard Minier, Dolina

* 2021

** 1-3. Philip Pullman, His Dark Materials (Northern Lights; The Subtle Knife; The Amber Spyglass)

Książki dla dzieci? No chyba żartujecie. Young adult — to już prędzej. Ale tak naprawdę powiedziałbym, że „Mroczne materie” wymykają się grupom docelowym: wyobrażam sobie, że przeczytałby je ze smakiem i inteligentny ósmoklasista, i ja, i ja na emeryturze. Może nawet John Milton, gdyby żył w naszych czasach. Bo duch Miltona przenika tu każdą stronę, a Pullman nie kryje inspiracji „Rajem utraconym”, łącznie z tym, że tytuł całej trylogii jest cytatem z tego dzieła.

To jest teoretycznie fantasy. Ale kiedy myślę „fantasy”, to nie mam na myśli niczego podobnego. Nie ma tu elfów, krasnoludów, czarodziejów ani magii takiej, o jakiej zwykle myślimy. Pullman nie stworzył dla tej książki jednego świata, tylko całe multiwersum rzeczywistości równoległych. Jest w nim nasz świat, są inne, jedne przypominające znaną nam rzeczywistość bardziej, inne mniej, pełne efemerycznych stworów i dziwnych krajobrazów. Wśród tych podobnych do naszego — ten świat, w którym rozgrywa się akcja całej „Zorzy północnej” i z którego pochodzi Lyra, główna bohaterka.

I chociażby dla samego tego świata warto to przeczytać. Z pozoru wygląda jak nasz, ale w miarę czytania wychodzą na jaw subtelne różnice. Oto wszyscy ludzie mają dajmony – zanimalizowane dusze, zwierzęta nierozdzielne z osobami, których są częścią. (Za tym faktem idzie misternie skonstruowany i wiarygodny kod kulturowy.) Oxford, rodzinne miasto Lyry, ma uniwersytet, w którym pierwsze skrzypce gra nieistniejący u nas college Jordana, a na nim badacze zajmują się ni mniej, ni więcej, tylko eksperymentalną teologią (po naszemu: fizyką). Rzeczywistość geopolityczna wygląda nieco inaczej: Kościół, rządzony z Genewy przez papieża i podległe mu instytucje, jest głównym aktorem na scenie politycznej, a gdzieś na wschodzie leży Moskowia. Zamiast czekolady pija się napój zwany chocolatl, a elektryczność nazywana jest anbarycznością (oba słowa wywodzą się od nazwy bursztynu — pierwsze z łacińskiego electrum, drugie przez angielskie amber od arabskiego عنبر‎, ʿanbar). Samolotów nie ma, za to po niebie latają balony, zeppeliny, żyroptery i machiny wojenne napędzane myślami. Daleka Północ — Svalbard i okolice — jest domem dla opancerzonych białych niedźwiedzi (Iorek Byrnison jest chyba moją ulubioną postacią w całym cyklu), a oprócz tego można się tu natknąć na gipcjan (rzecznych Cyganów), wiedźmy, anioły, duchy i inne istoty. Mnóstwo smaczków w tej steampunkowej rzeczywistości. Lubię.

Długo, długo można by pisać o tym świecie, a przecież jeszcze nie doszliśmy do fabuły — skonstruowanej nie mniej misternie. Nie będę tu spoilerować, powiem tylko, że chce się za nią podążać. Acz może się to zmieniać w miarę lektury, bo im dalej w cykl, tym bardziej szerokokątnym obiektywem obejmuje Pullman swój wieloświat i tym zawilej zaplatają się losy postaci. Język tych książek jest charakterystyczny i nader plastyczny. Trochę tę plastyczność mi się trudno przyswajało w dużej ilości naraz, ale nie uważam tego za wadę.

Dodatkowy bonus w wydaniu, które czytałem (Scholastic), to symbole na każdej stronie drugiego tomu i ekscentryczne typograficznie cytaty w tomie trzecim.

Serialu nie oglądałem. Chcę!

** 4. Josef Škvorecký, Przypadki inżyniera ludzkich dusz

Po tej lekturze odżyła we mnie dawna myśl, żeby kiedyś przeczytać Szwejka w oryginale. Czytałem tylko pierwszy rozdział, kiedyś, dawno, i zostało mi z niego wrażenie gawędziarskości. Takim samym słowem określiłbym „Przypadki…”: to książka gawędziarska.

Pierwsze, co rzuciło mi się w oczy, to tytuł pierwszego rozdziału: „Poe”. (W tytułach kolejnych rozdziałów mamy Hawthorne’a, Twaina, Conrada, Lovecrafta i tak dalej). Bo głównego bohatera, Daniela Smiřickiego, tytułowego „inżyniera”, czeskiego pisarza, literaturoznawcę, wykładowcę uniwersyteckiego i kobieciarza mieszkającego na stałe w kanadyjskim Mississauga, poznajemy na sali wykładowej, kiedy zagaduje swoich studentów (a zwłaszcza studentki) o znaczenie rozmaitych wyimków z literatury amerykańskiej.

Mieszają się w tej książce opowieści o literaturze z opowieściami o życiu – kulturalnym, salonowym i nie tylko – czeskiego środowiska imigranckiego w Kanadzie, a także ze wspomnieniami z czasów okołowojennych i cytowanymi in extenso listami. Czasem są wymieszane tak dobrze, że jedna historia płynnie (acz nie tak niepostrzeżenie jak u Cabrégo) przechodzi w drugą. Istny groch z kapustą: raz wzruszający, kiedy indziej śmieszny, to znów nudny i przegadany. To ostatnie by może mi bardziej przeszkadzało, gdyby fabuła miała wyraźnie zarysowane zawiązanie, zwroty akcji i na końcu efektywną pointę. Ale zupełnie nie o to chodzi. Miałem wrażenie, że siedzę w czeskiej gospodzie, wcinam knedliki, piję kufel piwa za kuflem i jestem zasłuchany w gawędę kogoś, kto umie opowiadać i przypominają mu się różne rzeczy. Wchodzi.

** 5. Selja Ahava, Rzeczy, które spadają z nieba

Jaka piękna niespodzianka!

Próbuję złapać, co mnie w tej książce zachwyca, i nie do końca umiem. Chyba piękna, mocna prostota narracji. Ze zwykłego życia, w którym z rzadka wydarzają się doniosłe momenty wywracające rzeczywistość do góry nogami – narratorka tka opowieść, którą czyta się jednym tchem. Nie jednym tchem: czasem robi się przerwy, żeby odetchnąć i zachwycić się tym czy owym zdaniem, obrazem, ostrością myśli.

Nie ma tu ani jednego niepotrzebnego słowa. Nawet w tytule, który brzmi metaforycznie, ale po przeczytaniu okazuje się, jak bardzo jest, nomen omen, przyziemnie namacalny. Trudno sobie wyobrazić, żeby mógł być inny.

Bardzo, bardzo polecam. 9/10.

** 6. Yōko Ogawa, Ukochane równanie profesora

Sympatyczne. Niezbyt głębokie, za to ciepłe i wzruszające. Rozgrzewająca książka w sam raz na chłodne jesienne popołudnie, do czytania pod kocem, z kubkiem herbaty.

Dla mnie dodatkowym źródłem radości było, że książka jest też o miłości do matematyki. Jeśli jednak zostaliście straumatyzowani w szkole, to może być trigger warning.

** 7. Ursula K. Le Guin, Lewa ręka ciemności

Jeśli Zajdel był mistrzem fantastyki socjologicznej, to powiedzieć o Le Guin „arcymistrzyni” byłoby jeszcze za mało. Im dalej zagłębiam się w „Ekumenę”, tym pod większym jestem wrażeniem. Ten tom bierze na warsztat płeć — to skomplikowane zjawisko biologiczno-kulturowo-społeczne — i daje bardzo wiarygodny portret społeczeństwa ambipłciowego, w którym męskość albo żeńskość nie jest przypisana do osoby raz na zawsze, tylko zmienia się z cyklu na cykl. Świetnie to się czyta.

Harold Bloom pisał, że Le Guin bardziej nawet niż Tolkien wyniosła fantasy do rangi literatury wysokiej. Nie mam najmniejszej wątpliwości, dlaczego.

9/10 (bardzo, bardzo mocne).

** 8. Blake Pierce, Idealna żona

Anglicy mają powiedzenie „what you get is what you pay for”: dostajesz to, za co płacisz. Przeczytałem to, bo wyskoczyło na mnie z oferty darmowych książek na Apple Books, i w trakcie lektury to porzekadło kołatało mi się po głowie.

Nawet wciąga, ale mam duże zastrzeżenia co do języka. Momentami miałem wrażenie, że tłumacz pomagał sobie Google Translate’em i nie wszystkie niedoróbki tłumaczenia maszynowego wygładził. Całkiem często pomieszane są zaimki i rodzaje gramatyczne — mówienie o kobiecych postaciach per „zrobił” — i nie, nie jest to świadomy zabieg.

** 9. Patrick Rothfuss, Imię wiatru

Bardzo fajne, soczyste fantasy. Gdzieś czytałem, że określana jest ta książka (i cała trylogia, której trzeciego tomu jeszcze nie ma) mianem „Harry’ego Pottera dla dorosłych” – to trafne porównanie ze względu na pewne podobieństwa fabularne, ale myślę, że znajdą tu coś dla siebie nawet ci, których książki Rowling nie porywają. Magia w tym świecie – jak i sam świat – jest porządna, mroczna, niszczycielska, zabójcza. A książka jest napisana tak, że chce się wiedzieć, co dalej. I – mimo objętości – kończy się za szybko. Chcę następne tomy.

** 10. W. L. Knightly, The Zodiac Killer

Kolejna z darmowych propozycji Apple Books. To thriller z szybką akcją, niezbyt wyrafinowany, ale czyta się. Miałem lepsze odczucia niż przy „Idealnej żonie” – może dlatego, że tu czytałem oryginał i nie było miejsca na kiksy translatorskie.

Niezłe wrażenie popsuła mi reklama na końcu, z której dowiedziałem się, że autor natrzaskał dwanaście następnych tomów, po jednym na każdy znak zodiaku. Mam skojarzenia z Remigiuszem Mrozem i to nie jest komplement.

** 11. Terry Goodkind, Gniazdo

Goodkinda znam z „Miecza Prawdy”, cyklu, który doczytałem jakoś tak do siódmej części. Pamiętam, że z tomu na tom podobało mi się coraz mniej, bo ileż w końcu razy główni bohaterowie mogą wplątywać się w coraz nowe tarapaty i ocalać świat od kolejnych szwarccharakterów – aż w końcu w szóstym tomie przyszedł twist, bo autor postanowił zrobić z książki traktat polityczny. Było to przerysowane, czarno-białe i naiwne, ale też była w tym jakaś świeżość.

„Gniazdo” mi trochę przypomina tamtą książkę. Niby to thriller kryminalny z galopującą akcją, ale autor próbuje się zmierzyć w nim z fundamentalnym pytaniem o źródło zła – i wkłada w usta jednego z bohaterów teorię próbującą na nie odpowiedzieć. W fabułę wpleciony jest wykład tej teorii i momentami czyta się to jak moralitet albo manifest kryminologiczno-psychologiczno-informatyczny (niezbyt przekonujący, dodajmy), a tempo akcji zwalnia do zera.

A jednak przy czytaniu zdarzyło się parę razy, że odłożyłem książkę na chwilę, żeby się zadumać. Jest w tym wartość. Jest też klimat i nieźle się to czyta.

Minus za wątek miłosny, sztampowy i przewidywalny do bólu. 6/10 (takie se).

** 12-14. Robin Hobb, Soldier Son Trilogy (Shaman’s Crossing; Forest Mage; Renegade’s Magic)

Pierwsze podejście do trylogii o żołnierskim synu, nieprzetłumaczonej jeszcze na polski, robiłem bodaj trzynaście lat temu. Kupiłem sobie wtedy na amsterdamskim lotnisku „Shaman’s Crossing” i przeczytałem, o ile pamiętam, z umiarkowanym zainteresowaniem. Nawet trochę mnie wciągnęło, ale poprzestałem wtedy na wrażeniu, że to nie ten poziom co skrytobójca czy żywostatki.

Teraz przeczytałem jeszcze raz cały cykl i z radością stwierdzam, że pierwsze wrażenia mylą. Z tomu na tom jest coraz lepiej. Ta trylogia się po prostu wolno rozkręca.

Przy okazji uświadomiłem sobie jeszcze raz, co mi wtedy zgrzytało. Nazwałbym to… wyblakłością świata tych książek.

Tak jak w „Uczniu skrytobójcy” lądujemy od pierwszych stron w żywym, barwnym świecie, skrzącym się od słońca i magii, ociekającym krwią, potem i intrygami – tak w „Shaman’s Crossing” mamy patriarchalne społeczeństwo, w którym wzrasta główny bohater, jakby wyjęte z wiktoriańskiej Anglii. Socjologicznie jest to skonstruowane ciekawie, jak to u Hobb: każdy syn rodziny szlacheckiej ma z boskiego nadania wyznaczoną rolę w społeczeństwie w momencie urodzenia. Każdy pierwszy syn rodzi się dziedzicem, drugi – żołnierzem, trzeci – księdzem, czwarty – artystą, i tak dalej.

Ale bóg tej religii określany jest po prostu jako „the good god”. Dni tygodnia nazywają się Firstday, Twoday, Threeday, Fourday, Fiveday, Sixday i Sevday. Dużo uwagi na początku poświęcone jest relacjom w rodzinie, w której chłopcy przyuczani są do swoich ról, dziewczynki do swoich (bycie żoną, prowadzenie domu i odwalanie niewidzialnej roboty) i wszyscy wszystkich karcą („rebuke”, ulubione słówko narratora). No jakbym czytał Thackeraya albo innego Dickensa. Jeśli ma się oczekiwania barwnego świata od pierwszej strony, można się zawieść: tu czytelnika wita sepiowy kurz prerii.

Im dalej jednak w cykl, tym bardziej ten świat wciąga, historia porywa i zżywamy się z głównym bohaterem, towarzysząc mu w jego drodze drugiego syna: w tym purytańskim domu, w akademii wojskowej, w kontaktach z magią (która, jak się okazuje, jednak jest), w snach, w kontaktach z innymi ludźmi i innymi kulturami, w przeorganizowywaniu pod ich wpływem własnego obrazu świata, w radzeniu sobie z niesprawiedliwością i okrucieństwem, w definiowaniu siebie na nowo, w osobistych tragediach, tęsknotach, ekstazach i zwycięstwach. To jest bardzo dobra obyczajowa fantasy. Jak to u Hobb.

Na koniec szczegół, który zapamiętam: szczególnie ważne jest w tych książkach jedzenie, fizjologiczno-sensoryczna czynność żywienia ciała. Narrator opowiada o nim często i bardzo zmysłowo. Nigdy nie czytałem tak opisywanego jedzenia. To ze mną zostanie.

** 15. Irvin D. Yalom, The Spinoza Problem

Problemem bodaj wszystkich Yalomowskich powieści jest język dialogów. I nie mam na myśli sposobu myślenia (nie dziwota, że Yalom mistrzowsko (re)konstruuje psychikę swoich bohaterów), tylko sam dobór słów. Ten zaś jest zbliżony u bodaj wszystkich postaci – mniej więcej taki, jakim mówi narrator w „Kacie miłości” albo „Istotach ulotnych”. Czasem przeszkadza to mniej, czasem bardziej, jak w „Problemie Spinozy” właśnie.

Może dlatego tu bardziej zgrzyta, że autor miał tym razem ciekawy pomysł na konstrukcję fabuły. Wyjaśnia to zresztą w przedmowie: książka wzięła się z próby odpowiedzi na pytanie, jak to się stało, że księgozbiór muzeum Spinozy w Rijnsburgu przetrwał II wojnę światową prawie nienaruszony mimo najazdu hitlerowców. Mamy więc dwa plany czasowe – jeden współczesny filozofowi i drugi, okołowojenny – i na przestrzeni trzystu lat i skrajnie różnych sposobów widzenia świata to podobieństwo stylów robi się bardzo dysonansowe.

Mimo wszystko warto, zwłaszcza jeśli lubi się Yaloma. Chociażby po to, żeby się dowiedzieć, kto to zacz Spinoza, potęga myśli co za.

** 16. Amor Towles, Dżentelmen w Moskwie

Zachwyt i wątpliwości towarzyszyły mi przy tej lekturze. Głównie zachwyt: językiem, jakim to jest napisane; klimatem tej historii (akcja prawie całej powieści rozgrywa się w jednym budynku — hotelu, w którym uwięziony jest główny bohater, hrabia Aleksander Iljicz Rostow — i jego oczami przez okna hotelu i przez wydarzenia w nim się rozgrywające patrzymy, jak się zmienia miasto, kraj, świat); wreszcie zachwyt postaciami, zwłaszcza zaś samym hrabią Rostowem i uosabianym przezeń etosem dżentelmena czy raczej rosyjskiego arystokraty.

I właśnie tu miałem wątpliwości. Nie co do obrazu rewolucji październikowej, wczesnych lat Kraju Rad i wielkiej czystki: nie, ta groza jest tu obecna w tle i jakkolwiek krew nie leje się gęsto, to echa represji słyszymy w wypowiedziach rozmówców Rostowa i natykamy się na osoby, które partia wywozi gdzieś na wieś i już nie wracają. Miałem wątpliwości co do etosu. Czy tacy arystokraci mogli w ogóle istnieć? Czy nieskazitelne maniery, poczucie honoru i kompas moralny Rostowa jakkolwiek współgrają z samą jego przynależnością do wyższych sfer? Czy możliwe, by olbrzymie nierówności społeczne schyłkowej carskiej Rosji w ogóle nie odcisnęły na nim piętna?

Myślę sobie, że czytając książki o obcych nam czasach czy warstwach społecznych mamy tendencję do generalizacji. „Aha, więc tak wtedy wyglądał świat i zachowywali się ludzie!”, choć przecież autor pokazuje nam ledwo wycinek świata, a bohaterowie niekoniecznie są reprezentatywni dla ogółu. Czy obowiązkiem autora jest reprezentatywność w imię wierności historycznej? Nie wydaje mi się. To raczej moją powinnością jako czytelnika, myślę, jest wyzbycie się założeń. Tak, żeby nie postrzegać hrabiego Rostowa jako modelowego arystokraty, tylko jako hrabiego Rostowa. Wspaniałą postać ze wspaniałą historią.

8/10 (mocne).

** 17. Jessie Burton, Miniaturzystka

Może i to ma sens, żeby nie spisywać wrażeń z lektury na bieżąco? Po kilku miesiącach one nie są wprawdzie tak żywe i wyraziste, ale za to lepiej widać, co zaciera się w pamięci, a co zostaje na dłużej.

Z „Miniaturzystki” został ze mną świetnie odmalowany obraz położenia żyjącej w XVII wieku młodej kobiety, świeżo wżenionej w amsterdamską bogatą rodzinę kupiecką: jej relacje z mężem, z innymi osobami zamieszkującymi nowy dom, z nowo poznawanymi znajomymi; proces kształtowania się i przeobrażania tych relacji i wchodzenia bohaterki w wielkomiejską socjetę; wreszcie odkrywanie granic możliwości własnego działania i kierowania swoim życiem. Zostało też ze mną wrażenie Amsterdamu jako miasta chłodnego i nieprzyjaznego.

Sama fabuła nieszczególnie mnie porwała; wątek tytułowej miniaturzystki wydał mi się nieco na siłę doklejony do akcji, a nie wpleciony w nią organicznie. Ale też nie to wydaje mi się w tej książce najważniejsze. Jako powieść obyczajową o społeczeństwie czytało mi się to dobrze. Trochę przypomina mi „Targowisko próżności”, choć brak tu takiej jak u Thackeraya potoczystości i rozmachu.

7/10 (krzepkie).

** 18. Lee Child, Czasami warto umrzeć

Jak to u Childa: ta książka to właściwie gotowy scenariusz filmu akcji. Która jak zwykle galopuje aż wiatr wieje, szwarccharaktery jak zwykle są obmierźli, a Jack Reacher jak zwykle zbawia świat (albo przynajmniej jego mały kawałek) bez mrugnięcia okiem. Po przeczytaniu szybko wylatuje z głowy i to nic nie szkodzi.

** 19. Stephen King, Billy Summers

Myślimy o Kingu jako o królu horroru, ale to nie wszystko. W „Jak pisać” King pokazał, że umie napisać autobiografię (tak, a nie jako poradnik dla początkujących pisarzy, odczytuję tę książkę), w „Mrocznej wieży” – że umie napisać fantasy, a w „Billym Summersie” – że umie kryminał. I to jaki kryminał!

Trochę staroświecki, trącący amerykańską powieścią drogi. Trochę psychologiczny: tytułowy Billy to płatny morderca, ale jego hierarchię wartości i motywy działania poznajemy na tyle wcześnie i są na tyle spójne, że chce się mu kibicować przez całą książkę. A do tego wszystkiego na wskroś Kingowski. Pyszności.

** 20. M. L. Longworth, Śmierć w Château Bremont

Chciałem lubić tę książkę. Kryminał, którego akcja rozgrywa się w Prowansji? Tak, poproszę! Taki z porządnym trupem na kilku pierwszych stronach, wartką akcją, opisami urokliwych prowansalskich krajobrazów i francuskimi kawiarenkami.

I niby wszystko to tu jest, ale takie jakieś… drętwe. Autorka wprawdzie zadbała o nadanie postaciom indywidualnych rysów, ale brak im głębi i charakteru; wydarzenia opisane są w sposób mało porywający, tak że miałem wrażenie pustosłowia. W którymś momencie zaczęło mi przeszkadzać słowo „szybko”, używane obficie dla podkreślenia tempa, z jakim bohaterowie robią to czy owo – w stężeniu nawet po kilka razy na stronę budzi to niesmak. (Teraz policzyłem: to słowo pada w książce aż 102 razy!)

Wikipedia mówi, że po sukcesie tej powieści powstało dziewięć następnych z Antoine’em Verlakiem w roli głównej. Dziękuję, postoję.

** 21. Ursula K. Le Guin, Wydziedziczeni

Mówiłem przy poprzednich częściach cyklu haińskiego, że z tomu na tom jest coraz lepiej i że Le Guin jawi mi się jako arcymistrzyni fantastyki socjologicznej. No więc niniejszym skończyły mi się słowa. I skala. Bardzo rzadko daję książkom 10/10 — to są w zasadzie książki życia, takie, które odcisnęły na mnie niezatarte piętno — a „Wydziedziczeni” wskoczyli na tę półkę tak lekkim susem, że aż prawie niezauważenie. I jestem pewien, że pozostaną tam na bardzo długo.

To jest książka totalna. Jak wszystkie poprzednie części cyklu, jest o komunikacji w obliczu barier kulturowych. Ale też o systemach społecznych, o kapitalizmie i komunizmie, o anarchii i plutokracji; o religii i nauce; o dobrobycie i ograniczonych zasobach; o feminizmie i wolności; o samotności i byciu w centrum uwagi; o miłości i tęsknocie; o zobowiązaniach i zaufaniu. Czytając „Wydziedziczonych” zadawałem sobie fundamentalne pytania o to, jak urządzić świat, żeby był jak najlepszy, i co to w ogóle znaczy „najlepszy” — i nadal nie wiem. Ale ta książka pokazała mi mnóstwo nowych stron, z których nie wiem, i to jest dla mnie wielka wartość.

A to wszystko zamyka się w ledwie trzystu kilkudziesięciu stronach, pozbawionych prawie w ogóle fajerwerków formalnych, stylistycznych i językowych. Jest tu tylko — i aż — żywa, bystra narracja prowadzona na dwóch przeplatających się planach czasowych. Czyta się to jednym tchem i byłaby to lektura na jeden wieczór, gdyby nie liczne przerwy na stawianie sobie pytań zasadniczych i kontemplowanie świata powieści i jej bohaterów.

Może lepszy świat to taki, w którym więcej osób przeczyta „Wydziedziczonych” i się nad nimi zaduma.

** 22. J. K. Rowling, Harry Potter i Czara Ognia

Im dalej w Harry’ego Pottera, tym mroczniej. To już nie jest ta na wskroś brytyjska bajka co w „Kamieniu filozoficznym”. Z tomu na tom Harry dorasta i nabiera doświadczenia (życiowego i magicznego), zagrożenie ze strony Sami-Wiecie-Kogo jest coraz bardziej namacalne, a na drugoplanowych Tych Złych zaczyna wyrastać Ministerstwo Magii. Upolitycznienie świata czarodziejów zaczyna mi coraz bardziej czytelniczo przeszkadzać, zwłaszcza że nie widać żadnego uzasadnienia dla wielu rządzących nim praw.

Przeszkadza to też Harry’emu, więc przynajmniej nie jestem sam. Pewnie doczytam do końca, ale bardziej siłą rozpędu niż z zaciekawienia.

** 23–24. Robert M. Wegner, Opowieści z meekhańskiego pogranicza (Północ–Południe; Wschód–Zachód)

Zacznę od czepiania się. Pytanie za sto punktów: jak wymówić tytuł? Czy podwójne e oddać w wymowie przez długie [iː], jak po angielsku, czy może przez [ɛː] jak po polsku? Czy zbitka ⟨kh⟩ wymawia się przydechowo, [kʰ], czy też może to [x], czyli polskie „ch” (w angielskiej ortografii transkrybowane czasem właśnie jako ⟨kh⟩)?

Idźmy dalej: pełne imię i nazwisko pierwszej postaci, którą poznajemy – porucznika dowodzącego jedną z kompanii Górskiej Straży – brzmi Kenneth-lyw-Darawyt. „Kenneth” brzmi jak angielskie imię, więc chciałoby się to wymawiać [ˈkɛnəθ], ale dla kontrastu zbitki -yw- i -wy- są zupełnie nieangielskie. Co z tym zrobić? Inne nazwiska w obszarze Imperium brzmią trochę z nordycka, jeszcze inne ze słowiańska – to się od biedy broni, biorąc pod uwagę wielokulturowość Meekhanu, ale jest dysonansowe.

Zostawmy na chwilę wymowę i zastanówmy się nad ortografią. Dlaczego to nazwisko jest trójczłonowe, ze środkowym członem wydzielonym dywizami i zapisywanym małą literą? Domyślamy się, że może to nazwisko szlacheckie i owo „-lyw-” jest markerem wysokiego pochodzenia, czyli czymś w rodzaju „von” czy „de” z języków europejskich. Tak, ale we wszystkich następnych meekhańskich nazwiskach, które poznajemy, ów środkowy człon jest inny – choć z jakiegoś powodu za każdym razem trzyliterowy! Dlaczego w takim razie go wyróżniać?

To samo z innymi nazwiskami. Na przykład imiona ludu Verdanno mają konsekwentnie postać: trzy litery, apostrof, reszta (np. And’ewers, Key’la). Co tu robi apostrof? W ortografiach w naszym świecie apostrof oznacza albo elizję jakichś głosek, albo zwarcie krtaniowe [ʔ], albo palatalizację (lub przeciwnie, welaryzację) następującej po nim spółgłoski. Teraz tak: jeśli to ma być elizja, to się zastanawiam, co jest zastępowane; jeśli [ʔ], to ono by się pojawiało w sąsiedztwie najdziwniejszych dźwięków; a znacznikiem palatalizacji nie może być, bo u Wegnera apostrof pojawia się w najróżniejszych kontekstach, również przed samogłoskami – i w ogóle zapis słów z tego uniwersum cierpi na apostrofozę.

I tak dalej, i tak dalej. Czytam ten cykl, czytam i się podskórnie zastanawiam nad takimi pytaniami. Jestem w połowie piątego tomu i nadal nikt mi na nie nie odpowiedział.

Ale! Ale skoro dojechałem tak daleko, to znaczy, że nie jest tak źle. W istocie wcale nie jest źle. Powiem więcej: jest bardzo dobrze.

Poniekąd typowo dla polskiej fantasy (Sapkowski zrobił to samo, podobnie Kres), swój cykl zaczyna Wegner od dwóch tomów luźno ze sobą powiązanych opowiadań (długich, ale jednak nie mikropowieści). Sprytny zabieg: dzięki temu w małych, łatwo przełykalnych kawałkach poznajemy świat – i to jaki świat! – jego geopolitykę, magię, bóstwa i inne siły nim rządzące. A także bohaterów, którym przyjdzie nam kibicować – i to jakich bohaterów! Choćby wspomniany Kenneth i reszta jego kompanii: to wojownicy z krwi i kości, charakterni, odmalowani tak żywo i barwnie, że Sienkiewicz by się nie powstydził. A Meekhan i inne kraje tego uniwersum są wymyślone z godnym podziwu rozmachem, solidnie i spójnie.

Do tego dochodzi cudownie zgryźliwy humor narratora i jego postaci. Świetnie jest to napisane, czyta się jednym tchem i chce się wiedzieć, co dalej. Drugi tom wydaje mi się nieznacznie słabszy, ale może to przez tęsknotę za Czerwonymi Szóstkami, które akurat mają w nim urlop.

Szczególnie w pamięć zapadło mi opowiadanie „Szkarłat na płaszczu”, świetne kompozycyjnie i każące Szóstkom i czytelnikowi zmierzyć się z niełatwymi wyborami moralnymi.

8/10 (soczyste).

** 25. Jo Nesbø, Pierwszy śnieg

Drugie, po projektoszekspirowym „Macbecie”, spotkanie z Nesbø i tym razem nie mam zastrzeżeń. Ze sprawdzonych składników (seria niewyjaśnionych morderstw powiązanych leitmotivem; postać głównego śledczego, z którą jesteśmy gotowi empatyzować, a trochę też podziwiać – choć może Harry Hole nie rysuje się tak swojską kreską jak Kurt Wallander u Mankella; sugestywna sceneria; wartka akcja z dużą ilością prawdziwych i fałszywych tropów) przyrządził autor smaczne danie. To nie jest wielka literatura, ale też i nie taka jest rola tej książki. Dobry kryminał na wakacje.

* 2020

** 1. Charles Willeford, Herezja oranżu palonego

Dobre, ale bez przesady. Krótkie i gęste. Czytając miałem myśl, że nie rozumiem sztuki współczesnej (a tym bardziej krytyki) i że można na jej polu zrobić coś takiego samego, co w ekonomii z systemem rezerw cząstkowych i pieniądzem fiducjarnym: skoro wartość dzieła bierze się z tego, czy mówi się o nim dobrze, czy nie, to czy samo dzieło jest do tego potrzebne? Oraz że nie lubię głównego bohatera. Po przeczytaniu nie lubię go jeszcze bardziej.

7/10.

** 2. Stephen Fry, Moab is My Washpot

Autobiografia Frya, a właściwie jej pierwsza część, obejmująca dzieciństwo i lata młodzieńcze. Czyta się równie dobrze, jak jego powieści, i znać tu podobne jak w nich wysmakowanie i wirtuozerię językową. Fry jako gawędziarz jest bardzo dygresyjny i opowieść stricte autobiograficzna – o dojrzewaniu, o rodzinie, o słowach, o seksualności – przeplata się tu z uwagami na temat różnych aspektów społeczeństwa brytyjskiego i społeczeństwa w ogóle. Bardzo warto.

** 3. Małgorzata Musierowicz, Szósta klepka

Dacie wiarę, że są na świecie ludzie, którzy nie czytali Jeżycjady? To znaczy nie wiem, czy jeszcze są, ale jeszcze kilka dni temu to byłem ja.

Myślę sobie, że miarą jakości książek „dla młodzieży” jest to, jak dobrze się je czyta, kiedy już nie jest się w wieku targetu. „Szósta klepka” ten test przechodzi z łatwością. Pochłonąłem w trzy wieczory, śmiejąc się i wzruszając na zmianę. Ale głównie się śmiejąc. Polecam. Li i jedynie.

** 4. Andre Dubus III, House of Sand and Fog

Gdybym miał to zaklasyfikować gatunkowo, powiedziałbym: thriller obyczajowy. Ze zmiennymi proporcjami: na początku bardziej obyczajowy, w końcówce bardziej thriller. Ważne w nim jest zderzenie kultur – research kulturowy został, mam wrażenie, przez autora odrobiony całkiem solidnie, nie miałem wrażenia stanocentryczności, a moje nastawienie do jednego z głównych bohaterów, irańskiego ekspata, wahało się od życzliwej ciekawości przez silną niechęć do współczucia. Jeśli autor umie tak zagrać na czytelniku, znaczy, że rzecz jest dobra.

Przeszkadzał mi trochę wątek miłosny/romansowy, nazbyt jak dla mnie nachalny i hollywoodzki. Ale tylko trochę.

** 5. Marta Guzowska, Ofiara Polikseny

Sympatyczne, lekkie czytadło, dobre na mrozy (akcja rozgrywa się w pełni lata w Turcji i żar leje się z nieba na każdej stronie). Uwaga, trzeba umieć się zdystansować od narratora! Fakt, że jest mizoginistycznym, ekhm, organem i nikt go w książce nie lubi, włącznie, mam wrażenie, z nim samym; ale opowiada o wydarzeniach na tyle lekkim, ciętym językiem, że mam spokojne zaufanie do autorki, że to celowy zabieg.

** 6. Guy Gavriel Kay, Fionavarski gobelin (Letnie drzewo; Wędrujący ogień; Najmroczniejsza droga)

O. Matko. Bosko.

Rzuciłem się na to, bo miałem świetne wspomnienia z przeczytanych kiedyś „Lwów Al-Rassanu”, a ludzie mówią, że „Pożeglować do Sarancjum” też dobre, i „Tigana”, i w ogóle… A powstrzymałem się od rzuceniem tego wielkiego tomiszcza (cała trylogia w jednej 1300-stronicowej cegle) i doczytałem do końca ze względu na trzy rzeczy: sunken cost fallacy; ciekawość fabuły i świata (to się ogólnie trzyma kupy i jest jedną z mocniejszych stron całości); oraz ciekawość, ile maksymalnie razy tłumaczce (Dorocie Żywno) uda się upchnąć na jednej stronie swoje ulubione słowo: „jednakże”.

Serio. Szacuję sumaryczną liczbę jednakżów w tej książce na tysiąc kilkaset. To słowo pada nie tylko do znudzenia w opisach, ale też w dialogach. Ludzie (i krasnoludy, i elfy, zwane dla niepoznaki lios/svart alfarami) tak do siebie tam mówią! Kapcie by mi spadły, gdybym je akurat miał na nogach, kiedy przeczytałem, że ktoś do kogoś powiedział „jednakże” w samym środku toczącej się bitwy!!! Z innymi słowami jest nie lepiej: tłumaczka nie potrafi napisać „prawie”, wszystko musi być „niemal”; nikt nikogo nie więzi, za to wszyscy wszystkich „spętują”, już od pierwszego zdania.

Drugi tom przetłumaczyła inna osoba i język tego tłumaczenia jest trochę lepszy, acz wydawca nie zadbał o to, żeby uspójnić pisownię okołofionavarskich słów i zwrotów (Jakuszewski pisze „aven” małą literą, a Żywno wielką; Jakuszewski pisze częściej „w Fionavarze”, a Żywno raczej „we Fionavarze” – wersja z wokalicznym przyimkiem akurat mi się całkiem podoba).

Ale całej winy na tłumaczy nie mogę zwalić, bo język dialogów jest niemożliwie drewniany, nadęty i nielogiczny. Próbowałem sobie wyobrazić, co trzeba mieć w głowie, żeby w danej sytuacji powiedzieć jedną czy drugą kwestię w stylu „Czy cofniesz swe słowa?” (otworzyłem losowo książkę na pierwszej z brzegu stronie, akurat s. 530).

To o tyle zastanawiające, że Kay miał całkiem ciekawy pomysł fabularny – piątka głównych bohaterów ląduje w/we Fionavarze przeniesiona z naszego świata, parę razy zresztą teleportując się tam i sam. I kiedy ci ludzie akurat są w Toronto, rozmawiają ze sobą jak ludzie i da się temu przysłuchiwać! A podobno Fionavar miał być pierwszym i najważniejszym ze światów, jądrem samego istnienia. Zamiast tego zastanawiałem się, jakim żywym cudem wszyscy tam mówią po angielsku i jak to się ma do tych swoistych nazw, które poznajemy i na podstawie których możemy się dorozumiewać, że „bael” to wojna, a prefiks „ta’-” oznacza grę/zabawę.

Mikrospoiler: motywy i postaci z legend arturiańskich są wplecione w fabułę na siłę i nieprzekonująco. Główny szwarccharakter, Rakoth Maugrim, prawie w książce się nie pojawia, ale jego widmo nie wisi nad Fionavarem tak namacalnie jak choćby widmo Saurona nad Śródziemiem. Ogólnie mam wrażenie, że Kay bardzo próbował być drugim Tolkienem, a wyszło jak zwykle.

Waham się, czy mocne 4/10 czy słabe 5/10. Jednak 5, za Paraiko i za ostatni kanior.

Aha, konkurs (mogłem coś przeoczyć) wygrała liczba 3. A gdyby liczyć dwie strony naraz, to 5.

** 7. Ferdinand von Schirach, Przestępstwo

„Zbrodnię i karę” czytałem w liceum (hm, może to jest pomysł na którąś z następnych lektur?) i pamiętam mgliście, a jednak ten zbiorek opowiadań mi się silnie kojarzył z Dostojewskim. Nawet tytuł jest z podobnej sztancy, zwłaszcza że drugi tomik von Schiracha nosi tytuł „Wina”. Mimo niewielkiej objętości to nie jest lekka i przyjemna literatura. To są opowiadania psychologiczne, z których każde stawia pytania, na które nie ma łatwej odpowiedzi.

Jeśli od kryminału oczekujesz wciągającej, skomplikowanej intrygi, wielu mylnych tropów, zwrotów akcji i odpowiedzi na pytanie „kto zabił?” nie wcześniej niż na ostatniej stronie – to nie ten adres. Jeśli chcesz się zadumać nad tym, jakie życie potrafi być pokręcone i popieprzone i jak nieoczywiste scenariusze potrafi pisać – polecam.

** 8. Dan Brown, Digital Fortress

Wyobrażam sobie, że jeśli nie ma się bladego pojęcia o informatyce ani kryptografii, można czytać tę książkę jak inne thrillery Browna – z zapartym tchem, śledząc galopującą fabułę i zwroty akcji o 180° i zagryzając paznokcie ze zniecierpliwienia. Tymczasem jeśli ma się blade pojęcie, to…

Szukam metafory. To nie jest grubymi nićmi szyte, bo efekt takiego szycia bywa mocny. Nie jest nawet poklejone taśmą klejącą – ani scotchem, ani chińską tandetą. Najlepsze, co mi przychodzi do głowy, to jakby pieczołowicie zrobić z zapałek feniksa i podpalić. Efekt jest spektakularny i dobrze się go ogląda, ale trwa krótko; zostaje zwęglony szkielet, który dość musnąć palcem, żeby całość rozsypała się w pył i wióry. Dla mnie ta lektura była ćwiczeniem z bardzo ostrożnego czytania, właśnie takiego, żeby nie dmuchnąć w niewłaściwą stronę.

Zrazu miałem myśli, że może to jest potrzebne. Może nadrzędnym celem było napisanie zajmującego technothrillera o kryptografii, może trzeba nagiąć rzeczywistość, żeby wyszło coś ciekawego i przyjemnego w odbiorze? Ale potem pomyślałem: e tam. Wyobraźmy sobie, że gdzieś w Pcimiu Dolnym jakiś student odkrywa szybką metodę faktoryzacji liczb pierwszych: to już jest zalążek, na którym można zbudować krzepki scenariusz, który będzie miał sens – i matematyczny, i przystający do rzeczywistości

U Browna najmniejszym problemem są zmyślone informacje, niemające pokrycia w rzeczywistości, a wprowadzone, jak się domyślam, po to, żeby fabuła miała jaki taki sens (nie ma czegoś takiego jak „zasada Bergofsky’ego”, a węgierski matematyk Josef Harne nie istniał i nie napisał w 1987 żadnego artykułu o „rotującym tekście jawnym”). Śmieszniej się robi, kiedy Brown strzela gafy w sprawach tak podstawowych jak to, czym się różni bit od bajtu (pisząc o „standardowym 64-bitowym kluczu”, gdy z kontekstu wynika, że chodzi o klucz składający się z 64 znaków) albo kiedy pisze o „256-znakowym alfabecie ASCII” (kod ASCII ma 128 znaków). Hasło „kryptografia z kluczem publicznym” objaśniane jest tak, że te klucze to takie długie i dlatego to jest trudne do złamania.

To wszystko jednak łatwe do naprawienia drobnostki w porównaniu ze spójnością fabuły. Oto NSA, amerykańska Narodowa Agencja Bezpieczeństwa (zatrudniająca główną bohaterkę – Susan, kryptografkę/programistkę, a jakże, piękną i genialną) konstruuje ściśle tajny superkomputer, TRANSLTR, którego zadaniem jest odszyfrowywanie przechwyconych zaszyfrowanych wiadomości. Komputer działa na zasadzie brute-force, czyli próbuje wszystkich możliwych kluczy, aż trafi na ten właściwy. Dzięki temu, że ma mnóstwo procesorów i jest taki równoległy, odszyfrowuje jeden plik za drugim w minuty. I nagle zonk: pojawia się plik, któremu TRANSLTR nie daje rady!

Na pytanie: „a co to znaczy, że plik jest odszyfrowany?” Brown macha rękami i plecie jakieś ogólniki o „rozpoznawalnych wzorcach słownych” (gdyby chciał, akurat teraz mógłby powiedzieć coś do sensu o estymacji entropii). A potem mówi, że ten niełamalny kod to dlatego, że nie wiadomo, kiedy jest złamany. No halo! To trzymałoby się kupy tylko wtedy, kiedy krok ewaluacji potencjalnego rozwiązania byłby zależny od czegoś innego poza tym potencjalnym rozwiązaniem, a to przecież nie ma sensu. Brown nigdzie też nie mówi, jak dokładnie działa ten brute-force (próbuje wszystkich znanych algorytmów i wszystkich kodów po kolei? w takim razie jak sobie radzi z trywialnymi tweakami algorytmów albo z plikami, które nie kodują niczego, tylko są po prostu losowymi ciągami liczb?)

Potem jest jeszcze ciekawiej, bo się okazuje, że wszyscy trzęsą portkami, że ten niełamalny kod to jakiś wirus. To miałoby jakiś strzęp sensu, gdyby TRANSLTR traktował podsuwane mu pliki jako kod wykonywalny (co to ma do kryptografii?), ale każdy średnio rozgranięty programista rozumiałby, że taki kod trzeba by puszczać w sandboksie z jakimiś ograniczeniami czasowymi, żeby nie wpadać w pętlę nieskończoną. Podobnie kiedy Susan próbuje odkryć prawdziwy adres e-mail, który się kryje za remailerem: nie potrafię wymyślić tych wszystkich „nawet gdyby”, które trzeba by dorysować, żeby to miało jakiś cień sensu. I tak dalej, i tak dalej.

Na osobnego ROTFL-a zasługują kompetencje tej bandy geeków (najtęższe umysły programistyczne/matematyczne na planecie). Susan jest bardzo zdziwioną kaczką, kiedy dowiaduje się, że program kodujący może być zakodowany sam sobą. Wiceszef NSA jest wybitnym programistą, ale nie może sobie poradzić z kodem Susan, bo nie zna składni tego języka programowania. I wreszcie créme de la créme: na samym końcu, pod presją czasu, kluczowa dla ocalenia świata okazuje się zagadka, do której rozwiązania potrzebna jest wiedza ogólna na poziomie VII klasy podstawówki i pół sekundy czasu na myślenie. I ta cała banda geeków nie może sobie z tym poradzić przez kwadrans!

Na końcu książki jest szesnaście liczb – kod do samodzielnego złamania przez czytelnika. Miła łamigłówka na dwie minuty.

** 9. Jaume Cabré, Podróż zimowa

Cabré w opowiadaniach jest trochę inny, niż w powieściach. Przy czym to jest kwestia formy, a nie autora: na kilkunastu stronach nie ma dość miejsca, żeby się porządnie rozcabrować, rozsnuć wiele wątków, planów czasowych, rozstawić postaci i rozpostrzeć na nich monumentalną opowieść. Te opowiadania to maleńkie kawałki świata, nie na tyle duże, żeby wpaść w nie całą sobą, ale tak napisane, że chce się je uważnie smakować. Przeczytałem w dwa dni, robiąc sobie po każdym przerwę, pięć-dziesięć minut na odetchnięcie, na przeżycie, na wybrzmienie.

Mimo ograniczeń formy Cabré znalazł sposób, żeby się nią po swojemu pobawić. Mimo że każde opowiadanie stanowi autonomiczną całość, one nie są całkowicie niezależne. Przeciwnie, są powiązane w bardzo subtelny sposób, jak sieć pajęcza. Główny bohater jednego może się pojawić gdzieś na obrzeżach drugiego, osobiście albo we wspomnieniach; bohaterowie są powiązani koligacjami rodzinnymi; powracają motywy, tropy, sekwencje dźwięków.

Protip: jeśli jest się smutnym, warto ominąć w pierwszym czytaniu opowiadanie VIII, „Pamiętam”; zatrąca o tematykę Szoah i mocno kopie w żołądek.

8/10 (bardzo mocne).

** 10. Zygmunt Miłoszewski, Uwikłanie

Pierwsze spotkanie z prokuratorem Szackim na plus. To kryminał, w którym w warstwie kryminalnej nie mam się do czego przyczepić. Wszystko jest jak trzeba: jest trup, jest śledztwo, są przeszkody, są mylne tropy i jest efektowne rozwiązanie zagadki na końcu. Ale podobały mi się w tej książce też inne rzeczy.

Po pierwsze, to, że główny bohater jest prokuratorem. Mam raczej mgliste skojarzenia z tym słowem — amerykańskie seriale sądowe, a w polskim kontekście upolityczniony urząd Prokuratora Generalnego — i nie miałem świadomości roli, jaką prokurator pełni u nas w śledztwie. Mam wrażenie, że Miłoszewski odrobił pracę domową przy riserczu; jest to napisane spójnie i wiarygodnie.

Druga rzecz to tło społeczno-geograficzne tej historii. Te mikroprasówki, którymi się zaczyna każdy rozdział, osadzające go w rzeczywistości, którą pamiętam jeszcze dość wyraźnie; to, którędy Szacki jeździ przez Warszawę; to, gdzie się tworzą korki i o czym mówi radio, kiedy samochód w nich stoi – wszystko to przywodziło mi na myśl z jednej strony kryminały skandynawskie (choć oczywiście z zachowaniem proporcji: Miłoszewski to nie Larsson, a Polska to nie Szwecja), a z drugiej „Złego” Tyrmanda: jak tamta, tak i ta książka ma za bohaterkę Warszawę.

I wreszcie to, że w fabule ważną rolę odgrywają ustawienia hellingerowskie. Temat śliski i zahaczający o pseudonaukę, ale poprowadzony umiejętnie, tak że nie odłoży książki z niesmakiem ani ktoś, kto odrzuca tę teorię jako programowo nieweryfikowalną, ani osoba, która uczestniczyła w tej formie terapii i ją sobie ceni.

Przeczytam następne tomy. Mocne 7/10.

** 11-13. Henryk Sienkiewicz, Trylogia (Ogniem i mieczem; Potop; Pan Wołodyjowski)

Co można czytać w łóżku, kiedy nie chce się zapalać światła, Kindle jest rozładowany, a do dyspozycji tylko telefon? Może na Wolnych Lekturach jest coś dla mnie? Hmm, „Ogniem i mieczem”… wieki całe nie czytałem Trylogii… „Rok 1647 był to dziwny rok…”

I dalej poszło. Samo się czytało. Ależ to jest page-turner!

Kluczem do Trylogii czytanej teraz, kiedy mam większy dystans do lektur i wyrosłem ze szkolnego bogoojczyźnianego patriotyzmu, jest nieocenianie. Bo w warstwie wartości jest toto głupie jak but: promuje uznawanie za coś zupełnie oczywistego, że ludzie się zabijają i krzywdzą z powodów kompletnie abstrakcyjnych, że wojny są dobre (o ile oczywiście wojuje się po Właściwej Stronie) i że za te abstrakty warto nadstawiać głowę. I tak, wiem, że pokrzepienie serc i w ogóle. Nie mam pojęcia, czy moje serce byłoby pokrzepione, gdybym się urodził przed stu trzydziestoma laty i czytał to w odcinkach drukowanych w prasie. Pewnie myślałbym inaczej.

No. W każdym razie trzeba to puścić, zaparkować głowę i pójść za tym, jak myślą i jak czują bohaterowie Trylogii. I wtedy, ach, jak to jest napisane, jakie malownicze! Kiedy Sienkiewicz pisze o tym, jak nad Dzikimi Polami świt wstaje mroźny, czuje się ten ożywczy mróz niemal namacalnie; kiedy akcja przenosi się nad rzekę, prawie słychać hurgot wód Dniepru przedzierających się przez porohy; w gospodach oczy czytelnika potrzebują dostosować się do półmroku, a uszy do hulanki i dudnienia kuflami o stół; a na wojnie ma się ochotę schylać głowę i uciekać przed hukiem dział i kartaczy. I oczywiście, że Kmicic ma twarz Olbrychskiego. Ale o ileż głębiej włazi się w ten świat, kiedy przy lekturze przebogate obrazy pojawiają się wprost w głowie!

Wystarczy mi na następne dwadzieścia lat, ale nie żałuję, że przeczytałem jeszcze raz.

** 14. Colson Whitehead, Kolej podziemna

Nie wszystko w tej książce wydarzyło się naprawdę. A jednocześnie nie ma w niej ani odrobiny kłamstwa. Czy to moja myśl, czy gdzieś to przeczytałem? (Zaglądam na okładkę: no tak, jest podobne zdanie w blurbie.)

Tytułową „koleją” nazywano w XIX wieku szlak ucieczki zbiegłych czarnoskórych niewolników z amerykańskiego Południa ku Północy, ku wolności sankcjonowanej prawem. To oczywiście przenośnia, ale u Whiteheada ona przybiera postać prawdziwej kolei podziemnej, takiej z zapuszczonymi stacjami, zbudowanymi dawno temu i doglądanymi z rzadka przez opiekunów, z ciemnymi tunelami ciągnącymi się przez setki mil i z rzadka przemykającymi po nich pociągami (jeden wagon, kilkoro pasażerów) albo drezynami.

Niesamowity zabieg: przez to, że odrealnia szlak ucieczki – urealnia drogę i czyni ją jeszcze bardziej namacalną. I od stacji do stacji, od miasta do miasta śledzimy na tym szlaku losy jednej osoby i towarzyszących jej ludzi. Czy można w ogóle uciec? Czy piętno jest wypalone na całe życie? Czy jest gdzieś jakaś wolność?

Kiedy to czytałem, przez świat przetaczały się protesty po śmierci George’a Floyda, pod hasłem Black Lives Matter. Mimo że akcja rozgrywa się w XIX wieku, każde słowo dźwięczało mi boleśnie aktualnie i przypominało o tym, że rasizm w Stanach nie skończył się ani wraz z przyjęciem 13. poprawki u schyłku wojny secesyjnej, ani w momencie rozwiązania Ku-Klux-Klanu w 1944, ani w 1968, kiedy zginął Martin Luther King i kiedy wszedł w życie ostatni akt prawny znoszący segregację rasową, ani też w latach 90., kiedy na drugim końcu świata likwidowano apartheid. Nie: ten rak nadal toczy amerykańskie społeczeństwo. I mało różni się od innych losów, które w innych częściach świata zgotowują ludzie ludziom tu i teraz.

To jedna z tych książek, które warto i należy przeczytać, żeby nie było za wygodnie. I żeby się przypomniały słowa Brodskiego:

    Ludzie giną, gdy do urny
    wrzucasz głos na nowych durni
    z ich nie nową już doktryną:
    „Nie tu giną”.

    […]

    Czas dzielący ludzkie byty
    na zabójców i zabitych
    zmieści cię w rubryce szerszej
    tak, w tej pierwszej.

** 15. Kelly Barnhill, Dziewczynka, która wypiła księżyc

Piękna i mądra baśń o nieposkromionej magii, o rodzinie, o odpowiedzialności, o trudnych wyborach i o girl power. A także o Wprost Olbrzymim Smoku i o tym, dlaczego należy uważać, kiedy śpi się z takim smokiem w jednym łóżku. Bardzo polecam.

** 16. Bjørn Larssen, Storytellers

Jeszcze zanim zacząłem czytać, wiedziałem, że mam osobne serce dla tej książki – a to z co najmniej trzech powodów. Raz, że dostałem e-booka na imieniny od Żony. Po drugie: książka należy do kategorii „prawie znam autora” – Ray (tak o nim myślę, choć to człowiek wielu profesji i wielu tożsamości) to znajomy moich znajomych, a bloga miloscpo30.net czytam i cenię od dawna. I wreszcie jest to powieść, której akcja rozgrywa się w miejscu, które odwiedziłem, zdeptałem własną stopą i mam stamtąd silne i żywe wspomnienia, czyli na Islandii. Podchodziłem więc do lektury z większą życzliwością niż zazwyczaj – i bez oczekiwań (bo po co). Gdybym je jednak miał, nie zawiódłbym się.

Islandia, marzec 1920. Zima ma się ku końcowi, ale dzień nadal jest krótszy od nocy, a surowa, wietrzno-śnieżna pogoda nie rozpieszcza. Jak może w taką pogodę spędzać wieczory kowal mieszkający samotnie na obrzeżach małej wioski, położonej o kilka godzin jazdy konnej od Reykjavíku? Może czytać albo pędzić życie towarzyskie? Tak, ale Gunnar nie lubi ani książek, ani ludzi, ani samego siebie. Jego jedynym towarzystwem jest pies, klacz, alkohol i depresja, otulająca go znajomym, chłodnym szalem ciemnych myśli. Kiedy więc któregoś dnia znajduje na progu swojej kuźni rannego nieznajomego, nie jest zadowolony. Pomaga mu wyzdrowieć tylko po to, żeby się go jak najszybciej pozbyć; zanim to jednak nastąpi, Sigurd, bo tak przedstawia się ów człowiek, zaczyna snuć opowieść…

Można by powiedzieć: powieść szkatułkowa. Nie znaczy to jednak, że „zewnętrzna” opowieść, ta o Gunnarze, jest ledwie pretekstem dla „wewnętrznej”. Nie: obie historie prowadzone są równolegle przez prawie całą książkę i wydawało mi się zrazu, że nie są ze sobą w żaden sposób powiązane. Im bardziej jednak zbliżałem się do końca, tym więcej mnożyło się niewiadomych w obu opowieściach, aż koniec końców okazało się, że te opowieści przenikają się i zaplatają w nader zakręcony sposób. Bardziej niż szkatułkę konstrukcja „Storytellers” przypomina mi więc butelkę Kleina.

O czym opowiadają „Opowiadacze”? O bezmiarze smutku, który człowiekowi może zalegać na dnie. (Postać Gunnara zostanie ze mną na długo, a to dzięki konstatacji, że nie trzeba głównego bohatera lubić – nie polubiłem go – żeby móc z nim silnie empatyzować.) O tym, co się dzieje, kiedy nie ma się przestrzeni na siebie. O marzeniach, miłości, fascynacji i zderzeniach z rzeczywistością. O tym, co może się stać, kiedy człowiek się tak bardzo zafiksuje na własnych myślach, przekonaniach, wspomnieniach i planach, że przestaje zwracać uwagę na świat. O stwórczej i niszczycielskiej mocy słów. I o Islandii, krainie zimna, bezkresu, surowego piękna i zórz.

Są w tej książce rzeczy, które mogą zgrzytać. Od początku moją uwagę zwrócił charakterystyczny styl narracji: precyzyjny, prawie techniczny. Zanim się do niego dostroiłem i wyczułem subtelną nutę ironii i humoru, miałem wrażenie, że to kwestia nienatywności (Ray napisał tę książkę po angielsku, choć jego językiem ojczystym jest polski), ale po paru rozdziałach się przyzwyczaiłem. Dalej: czytając miałem nieodparte wrażenie, że realia życia Gunnara i jego sąsiadów, choć są surowe, to jednak mniej, niżbym się spodziewał – i rzeczywiście, autor (który zrobił porządny risercz) w posłowiu wyjaśnia, że tę surowość nieco złagodził na potrzeby fabuły. Czasem miałem wrażenie, że bohaterowie zachowują się ni z gruszki, ni z pietruszki i że ich nie rozumiem: a potem myślałem sobie „taaaa, a w realu to może się zachowują do sensu?!” No i jest w książce jeden element fantastyczny, jakby wyciągnięty z innego zestawu klocków – a jednak jakimś przedziwnym trafem broni się.

7/10 czy 8/10? Chyba bardzo mocna siódemka. Ale jeśli widzieliście zorzę polarną i byliście pod wrażeniem, dopiszcie sobie punkt.

** 17. David and Leigh Eddings, The Redemption of Althalus

Kolejna z przeczytanych ostatnio książek, w których czułem się, jakbym wrócił do dawno niewidzianego, znajomego, przyjaznego miejsca. Myślę o „Belgariadzie” (i „Malloreonie”), w których zaczytywałem się w późnej podstawówce i wczesnym liceum, a zwłaszcza o charakterystycznym humorze przewijającym się przez te cykle: sarkastycznym, a jednocześnie prostym i dobrodusznym. „Odkupienie Althalusa” to opowieść z zupełnie innego świata, z innymi krainami, religiami i postaciami, ale humor jest tu ten sam. Podobnie jak potoczystość języka i „lubialność” bohaterów.

Wydawałoby się więc, że to książka do pochłonięcia w kilka wieczorów, prawda? Zwłaszcza że cała historia – rzecz niebywała u Eddingsów! – zamyka się w jednym, acz opasłym tomie. A jednak nie. Zaskakująco się męczyłem. I po przeczytaniu nie do końca wiem, czym. Możliwe, że stężeniem humoru (w „Belgariadzie” on był jednak trochę bardziej zróżnicowany i mniej nachalnie dawkowany, tu zaś prawie wszyscy rozmawiają ze sobą ze swadą i zgryźliwością charakterystyczną dla Silka/Kheldara). A może dlatego, że tak jak tam poszczególne krainy i nacje zarysowane były mocną, charakterną kreską, tak tu zlewały mi się ze sobą i stanowiły niezbyt wciągającą, jednorodną masę. Nieszczególnie zżyłem się z geografią, historią czy socjologią tego świata.

A jednak jest w nim dużo fajnych fabularnych pomysłów i krzepkich postaci, jak bohater tytułowy albo bogini Dweia, przez co nie miałem wrażenia, że czytam odgrzewanego kotleta opakowanego w nową okładkę. Mimo wszystko polecam, jeśli ktoś lubi Eddingsów. Mocne 6/10.

** 18–20. Robin Hobb, Bastard i Błazen (Skrytobójca błazna; Wyprawa błazna; Przeznaczenie skrytobójcy)

Robin Hobb dokonała czegoś niebywałego. Nie dość, że jest autorką najlepszego obyczajowego fantasy, jakie czytałem, a być może najlepszego fantasy w ogóle – to jeszcze ta monumentalna opowieść trzyma równy, wysoki poziom, przez bite dziewięć tomów. Co ja piszę: dwanaście! Bo to przecież nie tylko trzy trylogie o skrytobójcy, ale też żywostatki, które są bodaj jeszcze lepsze niż książki o Bastardzie. A może jeszcze cztery tomy “The Rain Wild Chronicles”, czyli, jak sądzę, “Kronik Deszczowych Ostępów”, które jeszcze nie wyszły po polsku i jeszcze ich nie czytałem. Mam nadzieję, że Agnieszka Ciepłowska nie powiedziała jeszcze ostatniego słowa w kwestii tłumaczenia Hobb.

Oczywiście, że zdarzają się górki i dołki (pamiętam, że “Wyprawa skrytobójcy” podobała mi się najmniej z pierwszej trylogii, podobnie “Przeznaczenie” z trzeciej), ale i tak czyta się całość z zapartym tchem. I wcale nie miałem wrażenia, że jest to przegadane, mimo że te tomiszcza liczą sobie po 800–1000 stron. I mimo, że przez większość “Skrytobójcy błazna” niewiele się dzieje, bohaterowie wiodą sobie spokojny żywot i dopiero na ostatnich może dwustu stronach akcja nabiera tempa. Wciąga jak bagno. Zwłaszcza po długiej przerwie od poprzednich trylogii: miałem wrażenie, jakbym wrócił do domu. Albo do dobrze znanego miejsca, gdzie się miło siedzi i spędza czas.

I tylko jedno przyprawia mnie o niesmak: Wydawnictwo MAG. Pięknie są te książki wydane, z ładną typografią, szyte, w twardych okładkach, a mimo to (i mimo objętości) wygodnie się je czyta; tym bardziej  kontrastuje z tym jakość redakcji i korekty, zjeżdżająca z tomu na tom na łeb na szyję – do naprawdę marnego poziomu. Chęć przyoszczędzenia? Pośpiech? Kilka, nawet kilkanaście literówek na tom byłbym w stanie wybaczyć. Ale kiedy na kilkunastu stronach ta sama klacz nazywa się raz Bryza, a raz Bystra, to mam powody przypuszczać, że ktoś się nie przyłożył do pracy; kiedy konsekwentnie powtarza się ten sam błąd składniowy (“zapomnieć” rządzi dopełniaczem, nie biernikiem, i kilka innych czasowników też!), to wiem, że bardzo się nie przyłożył; a kiedy zaczynają pojawiać się ordynarne błędy ortograficzne (“rządze” będą mnie nawiedzać w koszmarach), to zaczynam wątpić, czy jakakolwiek redakcja w ogóle miała miejsce.

Cieszcie się, państwo redaktorstwo i wydawnictwo, że taką beczką miodu są te książki, bo dzięki temu ten dziegieć tak bardzo nie przeszkadza.

** 21. Jaume Cabré, Cień eunucha

Cabré jak zawsze rewelacyjny (właściwie można by to skracać do CJZR, przyda się w kolejnych czytatkach – jeszcze co najmniej trzy jego książki przede mną). I jak zawsze soczysty. I jak zawsze o ludziach, ich historiach i emocjach. Miłość i śmierć. Muzyka i cisza. Przyjaźń i tajemnice. Wszystko to tutaj jest, prawdziwe, namacalne, magicznie przeżywalne.

Ta książka kojarzy mi się dodatkowo ze „Zwierzeniami klowna” Bölla. Jak tam, tak i tutaj oś fabularna jest bardzo prosta, minimalistyczna wręcz: przychodzi dwójka ludzi do restauracji i rozmawiają ze sobą przez całą książkę, jedząc obiad. (Trudno mówić i jeść naraz, więc obiad zasadniczo stygnie.) Mówi głównie on, Miquel o Wielu Przydomkach, główny bohater: raz, że obiad został zwołany w celu wspominania zmarłego przyjaciela, a dwa – że restauracja mieści się w domu, w którym Miquel się urodził i przeżył dużą część życia. I zza każdego rogu wyglądają wspomnienia, sięgające dwustu lat poprzez pokolenia wstecz. I jak to u Cabrégo, od zdania do zdania narracja przeskakuje między pokoleniami i bohaterami w sposób, który byłby chaotyczny, gdyby nie był tak konieczny do opowiedzenia tej historii.

Mam taką myśl, że ta książka może być dobrym wyborem na pierwszy kontakt z Cabrém. Ta historia nie jest aż tak obszerna jak w późniejszych powieściach, łatwiej, mam wrażenie, zapanować nad tymi przeskokami czasowymi, cały czas pozostajemy zasadniczo w obrębie jednego kraju i jednej kultury, no i dwieście lat to nie siedemset. Ale też mamy tu smaczki charakterystyczne tylko dla tej książki: struktura wpisana w konstrukcję konkretnego dzieła muzycznego, cytaty z tegoż dzieła (dosłownie z partytury!), no i przydomki!

9/10 (nie 10, bo gdyby miała być dycha, to dla „Wyznaję” zabrakłoby skali).

** 22. Jagoda Ratajczak, Języczni. Co język robi naszej głowie

Czy można władać dwoma językami, albo ich większą liczbą, równie biegle? Czy zawsze mamy „główny” język? Czy jeśli późno zaczynamy naukę, można w ogóle osiągnąć biegłość równą natywnej? Jak posługiwanie się wieloma językami naraz wpływa na mózg? A na funkcjonowanie w różnych kulturach?

O te i inne pytania zatrąca popularnonaukowa pogadanka Jagody Ratajczak. Tak: pogadanka, bo jeśli poszukuje się dogłębnych, wyczerpujących odpowiedzi, to nie ten adres. Za to dostajemy pięknie wydaną, fascynującą opowieść o języku i -języczności, do łyknięcia w jeden wieczór. Warto, jeśli lubi się język i nie jest specjalistką, chociażby po to, żeby zdać sobie sprawę z ogromu zagadnień, które porusza autorka.

** 23. Lee Child, Elita zabójców

Książki o Jacku Reacherze szybko się czyta i jeszcze szybciej zapomina. To nie do końca prawda, bo po paru miesiącach pamiętam zgrubny zarys fabuły i parę efektownych scen, ale brzmi chwytliwie.

Plus za smaczki matematyczne. Minus za nieudane tłumaczenie tytułu i kiksy redaktorskie, przez co niektóre zdania brzmią kulawo.

** 24. Clive Barker, The Great and Secret Show

Drugie po wielu, wielu latach podejście do „Wielkiego sekretnego widowiska”, tym razem w oryginale i tym razem udane.

Kojarzy mi się ta książka z małomiasteczkowymi powieściami Kinga spod znaku „Tego” albo „Sklepiku z marzeniami”: i tu zło wypełza na powierzchnię świata w małym kalifornijskim miasteczku. Ale Barker jest znacznie bardziej oniryczny, jego Ameryka przenika się z innym światem, takim z własną kosmologią, w którym czas, przestrzeń i życie rządzą się własnymi prawami.

Może się to podobać, może nużyć. Mnie się podobało i nużyło jednocześnie. Nie wiem, czy przeczytam następne tomy (choć „Everville” czeka na półce), ale się cieszę, że przeczytałem.

** 25. Randall Munroe, How to. Jak?

Tak!

Uwielbiam Munroe’a za myśli, które mu przychodzą do głowy. Na przykład: co by było, gdyby chcieć wygotować całą wodę z rzeki za pomocą zwykłych czajników elektrycznych? Albo za którym razem zawodowy tenisista trafi piłką w lecącego drona? (Autor najpierw wykonał stosowne obliczenia na papierze, a potem poprosił ni mniej, ni więcej, tylko Serenę Williams o eksperyment.)

Można by to nazwać absurdalnym humorem. Ale wolę myśleć, że Munroe przesuwa granice absurdu. Koniecznie, jeśli lubi się xkcd, „What If” albo „Tłumacza rzeczy”.

** 26. J. K. Rowling, Harry Potter i Kamień Filozoficzny
** 27. J. K. Rowling, Harry Potter i Komnata Tajemnic
** 28. J. K. Rowling, Harry Potter i więzień Azkabanu

Drugie po nie tak znowu wielu latach podejście do Harry’ego Pottera, tym razem w tłumaczeniu i tym razem udane.

O Harrym Potterze napisano już chyba wszystko, więc wydłubię tylko kąski, które mi szczególnie smakowały albo budziły zniesmaczenie. Tych drugich jest mniej i wynikają głównie z mojego przyzwyczajenia: przywykłem, że magia w fantasy jest czymś poważnym, czymś, przed czym odczuwa się naturalny respekt. A tymczasem… różdżki? Miotły? I zaklęcia składające się z dwóch słów z wykoślawionej łaciny? Serio?

No właśnie nie serio, bo to ma być fantasy dla dzieci. I jako taka sprawdza się świetnie, trzeba tylko uruchomić swoje wewnętrzne dziecko i przymrużyć oko pod odpowiednim kątem (albo założyć odpowiednie okulary. Oculus reparo!)

A najbardziej chyba mi się podoba to, że te książki są takie na wskroś brytyjskie. Każdy, kto kiedykolwiek wszedł do brytyjskiego pubu albo starego sklepu, wie, że jest to doświadczenie magiczne samo w sobie. A Rowling doskonale rozumie tę magię i wysyła ją na naturalny następny poziom z peronu 9¾ na King’s Cross.

Jestem też wielkim fanem słowniczków zamieszczanych na końcu każdego tomu. Andrzej Polkowski tłumaczy tam nie tylko, skąd się biorą te czy inne słowa, ale też uzasadnia niektóre swoje decyzje translatorskie. Brawo!

** 29. Guy Gavriel Kay, Tigana

Po nadętym i przekombinowanym „Fionavarskim gobelinie” podchodziłem do „Tigany” nieufnie. I z radością stwierdzam, że Kay się zrehabilitował z nawiązką.

Najkrótsza recenzja: na czas czytania tej książki zostałem nacjonalistą. To znaczy.

Oto półwysep, na którym współistniało dziewięć krajów, pada ofiarą inwazji z dwóch stron naraz i, podzielony, trafia w chwiejną równowagę sił między dwoma mocarstwami. Jeden z imperatorów żywi podsycaną żądzą zemsty nienawiść do jednej ze swoich nowych włości. I tak kraj, który kiedyś błyszczał świetnością swoich miast, pól i lasów, zostaje zniszczony, sprowadzony do roli podrzędnej prowincji, a pamięć o jego nazwie i istnieniu – siłą magii wymazana ze świadomości mieszkańców całego półwyspu. Historia zna przypadki damnatio memoriae pojedynczych władców czy wydarzeń; u Kaya na wieczne zapomnienie zostaje skazany cały kraj.

I jak tu nie kibicować ludziom, których czar nie objął i którzy spiskują ku naruszeniu owej chwiejnej równowagi sił?

Świetnie, barwnie, żywo napisana opowieść, inspirowana historią renesansowych Włoch. Jest tu świat, w który się wpada z uszami, a na nim miłość i nienawiść, lojalność i zdrada, sacrum i profanum: wszystko, czego chciałoby się od powieści fantasy o smaku historycznym. To więcej niż wciągające czytadło: to jest dobra książka.

** 30. Alistair MacLean, The Guns of Navarone

Rzadko czytam książki o wojnie, ale akurat wpadła mi w ręce najklasyczniejsza książka MacLeana. I nie żałuję.

Cofam się myślami o trzynaście lat, kiedy robiłem notatkę z przeczytanej właśnie „Ściany”, zbioru opowiadań Wasila Bykaua. Pisałem wtedy, że te opowiadania są prawie jak haiku: bardzo minimalistyczne. Jeden wątek, jedna historia, oszczędnie nakreślone tło, ani jednego niepotrzebnego słowa.

Podobne wrażenie mam teraz myśląc o „Działach…”. Nie ma tu wielu planów, nieliniowej narracji, szerokiego grona bohaterów. Nie trzeba. Jest jeden epizod, który nie wydarzył się naprawdę w II wojnie światowej, ale mógł. Jedna niewielka, górzysta wyspa na Morzu Egejskim u wybrzeży Grecji, dwa wielkie ufortyfikowane działa na niedostępnych klifach i zagrażające bezpieczeństwu alianckich okrętów – i piątka straceńców, którym przypada w udziale zadanie niewykonalne: wysadzić działa Nawarony jak Kmicic kolubrynę, unieszkodliwiając po drodze cały garnizon uzbrojonych po zęby Niemców jak Kuklinowskiego.

Siła dział tkwi w ich niedostępności (klify na prawie całej wyspie opadają ku morzu pionowymi, niezdobytymi ścianami). Siła „Dział”, mam wrażenie, też tkwi w niedostępności Nawarony, jakby wyłączonej ze świata i istniejącej jako jedyna we własnym wycinku rzeczywistości. Dzięki temu sceny, których jesteśmy świadkami, opisywane przez MacLeana językiem nader plastycznym – oszczędnym, kiedy trzeba, to znów pełnym pietyzmu – mrożą krew w żyłach przy najdrobniejszym potknięciu bohaterów. Najzupełniej dosłownie jak przy wspinaczce górskiej: bo któż inny, jak nie wytrawni himalaiści, mieliby cień szansy w takim położeniu?

I jak przy wspinaczce górskiej, tak tu absolutne zaufanie jest kluczową sprawą. Śpiewa mi w głowie Wysocki:

  Gdy nie skomlał, nie skarżył się,
  choć pochmurny i zły, lecz szedł
  i gdy nawet odpadłeś ty,
  to on drżał, ale trwał;
  jeśli z tobą jak w dym, tak gnał,
  a na grani się śmiał –
  wiesz, że możesz zaufać mu,
  tak jak sobie byś mógł.

Dodatkowy bonus mam taki, że nie widziałem filmu, dzięki czemu mogłem sobie namalować w głowie własną Nawaronę, zamiast widzieć tę Thompsona.

** 31. Ursula K. Le Guin, Miasto złudzeń

Dobrze, że nie czytam Ekumeny jednym ciągiem, bo chyba bym nie zdzierżył. UKLG to była ależ genialna kobieta. Za dobrze to jest napisane, za łatwo wchodzi, za dużo smutku naraz by się wchłaniało. Jeden tom naraz, z przerwami na mniej kamertonowe, poruszające książki, jest w sam raz.

Na razie mam wrażenie, że leitmotivem całego cyklu jest nieznośna trudność komunikacji – między jednostkami, ale też całymi gatunkami i rasami. „Miasto złudzeń” na tym tle przejmująco opowiada o poszukiwaniu własnym tożsamości i o kłamstwie.

8/10 (bardzo, bardzo mocne).

** 32. Ulrich Schnabel, Sztuka leniuchowania. O szczęściu nicnierobienia

Przeczytane bodaj trzeci raz i pewnie nie ostatni. Traktuję tę książkę jako część apteczki, skuteczne lekarstwo do zażywania (doocznie) tak często, jak trzeba, kiedy zapomnę, o co chodzi w życiu. Spoiler: nie o to, żeby zapracować i zastresować się na śmierć.

* 2019

** 1. Gene Wolfe, Miecz liktora

W zasadzie powinienem nie lubić Wolfe’a i „Księgi Nowego Słońca”, bo nie przepadam za oniryzmem. Wolę wiedzieć – albo przynajmniej domyślać się – o co chodzi, dlaczego wydarzenia mają miejsce i co z czego wynika, niż mierzyć się z lotnymi widziadłami, których znaczenie może wyjaśni się za kilkaset stron, a może wcale. Ale jest coś trudno uchwytnego w tych książkach, co mnie do nich przyciąga na przekór wszystkiemu. Styl? Język? Osobisty sentyment? Wrażenie obcowania z czymś mądrym, do czego potrzebuję doskakiwać? A może to, że mimo całej masy niewiadomych kawałki treści układają się w logiczny ciąg na tyle wyraźny, żeby chcieć za nim jednak podążać? W „Mieczu…” jakby wyraźniejszy niż w poprzednich tomach. Pewnie przeczytam też „Cytadelę Autarchy”, ale nie od razu.

** 2. Sakyō Komatsu, Zatonięcie Japonii

Nie będzie spojlerem, jeśli powiem, że ta książka jest dokładnie o tym, o czym mówi tytuł. Nie czekamy do ostatniej strony niecierpliwie oczekując rozwiązania zagadki, bo wiadomo, jak to wszystko się skończy: Japonia zatonie. Ciekawsze jest, dlaczego to się wydarza, jakie wydarzenia poprzedzają ten kataklizm i jak to wszystko wpływa zarówno na pojedyncze osoby, jak i na całe społeczeństwo.

Czyta się to bardzo nierówno. Momentami lektura jest równie pasjonująca jak słuchanie wykładu uniwersyteckiego, oglądanie transmisji z obrad parlamentu czy czytanie rocznika statystycznego – i to dosłownie, kiedy odpowiednio autor pokazuje nam przemowę naukowca (tak, to jest hard SF z elementem „science” tak przenikającym całą rzecz, jak rzadko), spotkania polityków albo wymienia miejscowości, które ucierpiały w tym czy owym trzęsieniu ziemi. Ale bywa, że narracja uderza w ton nostalgicznie-poetyczny à la Murakami.

Mimo wszystko cieszę się, że przeczytałem. Chyba najciekawszy, mimo oschłości języka, wydał mi się komponent socjologiczny całości: o tym, jak się zachowuje społeczeństwo w obliczu narastającego zagrożenia.

** 3. Tess Gerritsen, Igrając z ogniem

Są książki, których lektura wymaga pewnego wysiłku, i są takie, które „same wchodzą”. To oczywiście zależy od odbiorcy, ale dla mnie „Igrając z ogniem” należała do tej drugiej grupy. Przypomniałem sobie, jak fajnie jest pochłonąć książkę w trzy wieczory. Zwłaszcza że to jest niegłupie, fajnie skomponowane czytadło: o kontakcie z rzeczywistością, o tym, co się dzieje z relacjami w obliczu kryzysu, o Shoah, o Wenecji i przede wszystkim o muzyce i o tym, jak ona potrafi budować mosty przez czas i przez przeżerającą społeczeństwo pogardę.

Tylko, pani autorko, tego, co pani zrobiła w pierwszym rozdziale, nie robi się kotu.

** 4. Kate Mosse, The Winter Ghosts

Tak wyszło, że równolegle czytałem dwie książki, których akcja rozgrywa się prawie w tym samym miejscu: u stóp Pirenejów po dwóch stronach granicy francusko-hiszpańskiej. Ta jest francuska. Prosta opowieść o żałobie, samotności i ulotnym uczuciu, które łatwo można pomylić z miłością.

Podobało mi się, że tytuł wiernie oddaje dojmujący klimat bijący ze stron książki. Jest zimno, grudniowo, cicho i martwo, prawie nie wieje wiatr i nawet ludzie, których spotyka główny bohater, są milkliwi i zamknięci w sobie. W taką zimę najdrobniejszy szelest zastyga w powietrzu i niesie się przez stulecia.

A z drugiej strony, mimo że to krótka opowieść, miałem wrażenie, że jest w niej mnóstwo niepotrzebnych słów. Jakby ktoś opowiadał nagranie z kamery przemysłowej. Naprawdę nie trzeba było z pietyzmem opisywać każdego doznania bohatera, każdego zmęczonego kroku, koloru i faktury jego odzieży czy kamieni, o które akurat się opiera. To przegadanie odbiera mu wiarygodności, bo lwia część narracji prowadzona jest w pierwszej osobie, z perspektywy wspomnień po pięciu latach; taka dokładność i potoczystość języka jest do pomyślenia, gdyby szło o pojedyncze chwile, które odcisnęły się niezacieralnie na umyśle bohatera, ale nie w przypadku całego miesiąca. Zostałem z przykrym wrażeniem, że wydawca do spółki z autorką bardzo chcieli zrobić książkę z mikropowieści.

** 5. Jaume Cabré, Głosy Pamano

Wyznaję, że po wspaniałym „Wyznaję” miałem obawy, czy Cabré nie jest pisarzem jednej książki: czy to czasem nie jest tak, że ani przedtem, ani potem nie zdarzy mu się nic równie dobrego. Jak z tym „potem”, nie wiadomo, ale w kwestii „przedtem” („Głosy Pamano” są wcześniejsze, choć później u nas wydane) oddycham z ulgą i stwierdzam, że autor doskoczył sam do swojej poprzeczki. Kto czytał „Wyznaję”, ten się w „Głosach…” odnajdzie natychmiast. Jest tu niekonwencjonalna cabrowska interpunkcja, jest narracja na wielu planach czasowych naraz, jest charakterystyczny, smakowity, soczysty cabrowski język, są żywe, z krwi i kości osoby i są ich historie i ich emocje prawdziwe i głębokie do bólu.

Niby wydaje mi się, że „Wyznaję” jest głębsze, bardziej wielowarstwowe; ale z drugiej strony to chyba powiew świeżości wywołany tym, że nikt inny tak nie pisze. Całkiem możliwe, że gdybym je czytał w odwrotnej kolejności, to właśnie przy „Głosach” miałbym opad szczęki do ziemi, po którym trudno się pozbierać. Niczego jej nie brakuje. 10/10.

** 6-7. Jo Nesbø, Macbeth; William Shakespeare, Makbet

Pierwsza powieść z „Projektu Szekspir” i zarazem pierwsza książka Nesbø, którą przeczytałem. Mam mocno mieszane myśli.

Podobał mi się sztafaż. Mamy tu prawie wszystkie postaci z oryginału, w nieznacznie zmienionych rolach: Duncan jest komendantem policji, Makbet, Banko, Makduf i inni – policjantami, Hekate – bossem gangu narkotykowego, Trzy Wiedźmy – dealerkami, a Lady Makbet – właścicielką kasyna. Pomysł smakowity, a  pościgi, strzelaniny i wartka akcja, w której trup ściele się gęsto – gwarantowane. Pod tym względem autor nie zawodzi. Można się poczuć, jakby oglądało się film akcji, zwłaszcza że Nesbø ucieka się do całkiem kinowych trików. To też może się podobać.

Parę rzeczy mnie nie przekonało. Akcja rozgrywa się prawie w całości w bliżej nieokreślonym mieście, którego nazwa nigdy w powieści nie pada, w jakimś fikcyjnym państwie (można się domyślać, że przypominającym Stany, choć ze szkockimi nazwami geograficznymi), którego stolica nazywa się Capitol. Zaskakująco przeszkadzała mi ta fikcyjność, oderwanie od rzeczywistości. Granice świata książki wyznaczają granice miasta, co uniewiarygadnia przekaz (raz, że poza miastem o świecie przedstawionym nie wiadomo prawie nic i ta czarna dziura jest niemal namacalna, a dwa – że gdyby to faktycznie były Stany, to nie wierzę, żeby przy takiej skali lokalnego smrodu nie interweniowali federalni).

To jednak drobiazg. Większy problem miałem z tym, co w dużej mierze stanowi o wartości tragedii Szekspira: z warstwą psychologiczną, z przemianą Makbeta z oddanego funkcjonariusza w bezwzględnego psychopatę, z relacją między Makbetem a Lady. Powiem krótko: to mnie nie przekonuje. Walka Makbeta z wewnętrznymi demonami, u Szekspira niemal namacalna w monologach i strzępkach myśli, u Nesbø wypada płasko i niewiarygodnie; to zaś, co u Szekspira ledwie zarysowane, w wersji powieściowej jest przejaskrawione i sprawia wrażenie karykatury.

Na koniec przeczytałem oryginał. Warto. Będę też tak robił z następnymi projektoszekspirowymi książkami. Jeśli chcecie przeczytać Makbeta, czytajcie raczej „Makbeta”, a nie „Macbetha”. (Uwaga na tłumaczenie: omijajcie z daleka Słomczyńskiego i czytajcie Barańczaka, ew. Paszkowskiego.)

** 8. Wars B. Niańcz-Sałatka, Zgap łabędzie, vel A.S. Zasrańc-Bławatkin, Diabeł zęz gap, vel Stanisław Barańczak, Pegaz zdębiał

Barańczak. Nic więcej nie trzeba mówić. Właściwie za recenzję mogłoby robić nagranie salw śmiechu tudzież nieudanie tłumionych parsków spod kołdry (żeby nie budzić osoby śpiącej obok). Napiszę tylko, że czytałem najnowsze wydanie Agory, zredagowane przez Joannę Szczęsną, z obfitym wstępem, dwoma czy trzema dodatkowymi rozdziałami i notami redaktorskimi po każdym rozdziale. Więcej niepublikowanych bezsensów, więcej zabawy językiem, więcej śmiechu. Samo dobro.

** 9. Stephen Fry, Making History

Strasznie się cieszę, że nie przeczytałem żadnej recenzji przed skończeniem książki. Po przeczytaniu zajrzałem do kilku, żeby zobaczyć, czy wrażenia recenzentów pokrywają się z moimi, i we wszystkich były spoilery. Na szczęście blurb na okładce nie popełnia tego błędu, zdradzając tylko, że to powieść SF – choć przez pierwszych sto stron nic nie zdradza tej przynależności gatunkowej – i miałem satysfakcję ze zgadnięcia tematu Meisterwerk głównego bohatera, zanim został on nazwany w tekście wprost.

Język, jakim to jest napisane, urzekł mnie od pierwszego zdania (chociaż efekt „wow” osłabł mniej więcej w połowie, ale to pewnie dlatego, że się przyzwyczaiłem – tak to bywa z zachłyśnięciami). Jest potoczysty, miejscami wręcz slangowy (to naturalne w obliczu narracji pierwszoosobowej), czyta się lekko, a jednocześnie unika miałkości i braku głębi właściwego wielu czytadłom: Fry nie waha się sięgnąć po rzadko używane, wyszukane słowo, jeśli jest ono akurat właściwe. I mnóstwo w tym języku i w tej książce znaku rozpoznawczego Frya, czyli humoru. Bardzo angielskiego, pełnego ironii i dystansu do świata.

W jednej z recenzji znalazłem zniesmaczenie tym, że ów humor wydaje się niewłaściwy w obliczu wielkich tragedii, o których również jest ta książka – tragedii zgotowanych ludziom przez ludzi. Nie zgadzam się. W moim czytaniu autor umiejętnie go ześrodkowuje na konkretnych ludziach, sytuacjach albo na języku, zachowując jednocześnie powagę w obliczu tego, o czym trzeba mówić poważnie. Za to doceniam fakt, że jak wiele dobrych książek, tak i ta stawia ważne pytania, na które nie ma jednoznacznych odpowiedzi. Nie powiem, jakie, bo nie chcę spoilerować.

Druga, po Cabrém, najlepsza książka przeczytana w tym roku. 9/10.

** 10. Andy Weir, Marsjanin

Blast from the past. Zjadłem tę książkę w dwa dni, czując się, jakbym jeszcze raz czytał „Tajemniczą wyspę” Verne’a, tylko że w sztafażu hard SF. To samo prawie beznadziejne położenie głównego bohatera i ten sam niezłomny charakter. Plus humor! Poczucie humoru i dystans do siebie Marka jest równie kluczowe dla jego przetrwania jak woda, pożywienie i powietrze, i ten humor w dużej mierze odpowiada za to, jak lekko to jest napisane. I nawet kiepska jakość przekładu/korekty (to nieszczęsne sianie ziemniaków!) mi szczególnie nie przeszkadzała. Smakowitość.

** 11. Peter James, Pogrzebany

Przyjemne, wciągające czytadło, które nie próbuje udawać nic więcej. Nietrafione tłumaczenie tytułu (w oryginale „Dead Simple”) pozwala podejrzewać, że i w treści parę gagów przepadło w przekładzie, ale i tak spędziłem z tą książką parę miłych wieczorów.

** 12. Lorrie Moore, Kora

** 13. Jerome K. Jerome, Trzech panów w łódce (nie licząc psa)

** 14. Renée Knight, Sprostowanie

** 15. Matthew Kneale, Anglicy na pokładzie

** 16. Cixin Liu, Problem trzech ciał

To druga od paru lat (po „Marsjaninie”) książka hard SF, którą przeczytałem. Początki były trudne: przez pierwsze kilkanaście czy kilkadziesiąt stron miałem wrażenie, że czytam jedną z tych książek o wojnie z serii „z tygrysem”, w których kiedyś zaczytywał się mój dziadek. Ale kiedy zacisnąłem zęby i poszedłem dalej, okazało się, że wciąga, że ta wojenna część jest potrzebna (to nie tylko fantastyka, to też wnikliwe socjologiczne spojrzenie na współczesne Chiny i na Chiny z czasów rewolucji kulturalnej), że tchnie świeżością i to nie tylko ze względu na egzotykę kraju pochodzenia autora i kraju akcji, ale przede wszystkim świeżością spojrzenia na – wydawałoby się – do cna wyeksploatowany temat kontaktu z obcą cywilizacją.

Chyba największe wrażenie zrobiła na mnie atmosfera całej historii. To jest zimna opowieść, pełna smutku, lęku i niemal namacalnej niepewności. Zostanie ze mną na długo.

** 17. Richard Adams, Maia

Czytałem to opasłe tomiszcze (1130 stron) przez ładny kwartał, mając przez cały czas mieszane wrażenia. Po zakończeniu lektury mam je nadal.

Na plus: wciągająca historia i jej rozmach. Beklańskie imperium wrze od brudnych, politycznych intryg, a główna bohaterka zostaje wrzucona w sam ich środek; to jest coś, co można śledzić z zaintrygowaniem, ten świat jest skonstruowany wiarygodnie i z dbałością o szczegóły. Przez cały czas byłem ciekawy, co dalej, zwłaszcza przez ostatnie czterysta stron – to nie lada osiągnięcie przy powieści o takiej objętości. Widać też, że to Adams: podobnie jak w „Wodnikowym Wzgórzu”, mamy tutaj opowieści czy gawędy bohaterów zajmujące cały rozdział, mamy też lingwistyczne smaczki w stylu wybranych słów z języka imperium (zwłaszcza związanych z seksem, ciekawe dlaczego…) używanych konsekwentnie w tekście czy honoryfikatywów w dialogach. Lubię.

Co mi się nie podobało: no właśnie, seks. Żeby był konsensualny, to byłoby fajnie, ale mnóstwo w tej książce przemocy seksualnej. Kiedy czytam, że bohaterka zostaje rozdziewiczona w wieku piętnastu lat przez własnego ojczyma i wywiązuje się między nimi coś w rodzaju romansu, i że wszystkie postacie w książce (a także najwyraźniej narrator) uważają za rzecz absolutnie oczywistą, że kobieta automatycznie pała uczuciem do faceta, który posiądzie ją pierwszy, to trudno mi to traktować inaczej niż jako mokre fantazje autora. W ogóle warstwa psychologiczna jest uboga i mało wiarygodna, a bucowate wstawki narratora w stylu „świat działa tak a tak” budziły mój niesmak. Tym bardziej to dziwne, że część postaci jest odmalowana żywo i charakternie; niestety nie należy do nich tytułowa bohaterka, którą przez całą książkę miota los i jej świadome czyny można policzyć na palcach jednej ręki.

Ogólnie, jeśli ktoś czytał „Szardika” i chce jeszcze raz zajrzeć do tego świata (to ten sam świat co w „Mai”), to można, ale to zdecydowanie nie jest pozycja obowiązkowa.

** 18. Gaston Dorren, Babel. W dwadzieścia języków dookoła świata

Kopalnia ciekawostek. Warto, jeśli ktoś się interesuje językami albo kulturami, albo tym, w jaki sposób jedne i drugie wzajemnie na siebie oddziałują. Bardzo warto, jeśli, tak jak ja, ma się hysia na punkcie któregoś z tych tematów. Trochę zaskakująca była dla mnie niejednolitość tematyczna: niektóre rozdziały (jak te o wietnamskim czy hiszpańskim) są o językach jako takich, inne (jak rozdział o tamilskim) to opowieści socjopolityczne z językiem w tle.

** 19. Ursula K. Le Guin, Nie ma czasu. Myśli o tym, co ważne

* 2018

** 10–13. Jarosław Grzędowicz, Pan Lodowego Ogrodu (I–IV)

Wymęczyłem się. To jest pełnokrwista, soczysta fantasy, acz na mój gust za dużo tu ordynarnej siekaniny (pieczołowicie za każdym razem opisywanej) i trudnego do śledzenia, niezrozumiałego oniryzmu. Nie do końca trafia do mnie też określanie cyklu Grzędowicza jako traktatu politycznego: gdybym chciał czytać o systemach politycznych, spodziewałbym się czegoś bardziej analitycznego i dogłębnego. Niemniej dostałem kawał wciągającej i trzymającej w napięciu literatury.

** 14. Dopóki życie trwa
Trzyma bardzo wysoki poziom pierwszej części i jest tak samo przepełniona radością życia, smutkami i wzruszeniami. Hendriku Groenie, dwieście lat!

** 15. Irvin D. Yalom, The Schopenhauer’s Cure
Siedzi kilka osób w jednym pokoju i rozmawiają przez całą książkę (z drobnymi wyjątkami). Ze względu na relacje między tymi osobami, to, co się dzieje w głowie każdej z nich i to, co wyłazi w owym pokoju (który, jak łatwo zgadnąć, jest salą terapii grupowej, w końcu to Yalom) – wychodzi fascynujący miszmasz. Bardzo warto; dla mnie lepsze nawet niż „When Nietzsche Wept”.
